// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notify.proto

package eventpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotifyRequest_Type int32

const (
	NotifyRequest_SECURITY NotifyRequest_Type = 0
)

var NotifyRequest_Type_name = map[int32]string{
	0: "SECURITY",
}

var NotifyRequest_Type_value = map[string]int32{
	"SECURITY": 0,
}

func (x NotifyRequest_Type) String() string {
	return proto.EnumName(NotifyRequest_Type_name, int32(x))
}

func (NotifyRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{0, 0}
}

type NotifyRequest_Level int32

const (
	NotifyRequest_INFO     NotifyRequest_Level = 0
	NotifyRequest_LOW      NotifyRequest_Level = 1
	NotifyRequest_MEDIUM   NotifyRequest_Level = 2
	NotifyRequest_HIGH     NotifyRequest_Level = 3
	NotifyRequest_CRITICAL NotifyRequest_Level = 4
)

var NotifyRequest_Level_name = map[int32]string{
	0: "INFO",
	1: "LOW",
	2: "MEDIUM",
	3: "HIGH",
	4: "CRITICAL",
}

var NotifyRequest_Level_value = map[string]int32{
	"INFO":     0,
	"LOW":      1,
	"MEDIUM":   2,
	"HIGH":     3,
	"CRITICAL": 4,
}

func (x NotifyRequest_Level) String() string {
	return proto.EnumName(NotifyRequest_Level_name, int32(x))
}

func (NotifyRequest_Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{0, 1}
}

type NotifyRequest_Data_DataEnc int32

const (
	NotifyRequest_Data_NODATA NotifyRequest_Data_DataEnc = 0
	NotifyRequest_Data_JSON   NotifyRequest_Data_DataEnc = 1
)

var NotifyRequest_Data_DataEnc_name = map[int32]string{
	0: "NODATA",
	1: "JSON",
}

var NotifyRequest_Data_DataEnc_value = map[string]int32{
	"NODATA": 0,
	"JSON":   1,
}

func (x NotifyRequest_Data_DataEnc) String() string {
	return proto.EnumName(NotifyRequest_Data_DataEnc_name, int32(x))
}

func (NotifyRequest_Data_DataEnc) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{0, 1, 0}
}

type NotifyRequest struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 NotifyRequest_Type    `protobuf:"varint,2,opt,name=type,proto3,enum=luids.event.v1.NotifyRequest_Type" json:"type,omitempty"`
	Code                 int32                 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Level                NotifyRequest_Level   `protobuf:"varint,4,opt,name=level,proto3,enum=luids.event.v1.NotifyRequest_Level" json:"level,omitempty"`
	Timestamp            *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source               *NotifyRequest_Source `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Data                 *NotifyRequest_Data   `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NotifyRequest) Reset()         { *m = NotifyRequest{} }
func (m *NotifyRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyRequest) ProtoMessage()    {}
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{0}
}

func (m *NotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRequest.Unmarshal(m, b)
}
func (m *NotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRequest.Marshal(b, m, deterministic)
}
func (m *NotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRequest.Merge(m, src)
}
func (m *NotifyRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyRequest.Size(m)
}
func (m *NotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRequest proto.InternalMessageInfo

func (m *NotifyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NotifyRequest) GetType() NotifyRequest_Type {
	if m != nil {
		return m.Type
	}
	return NotifyRequest_SECURITY
}

func (m *NotifyRequest) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *NotifyRequest) GetLevel() NotifyRequest_Level {
	if m != nil {
		return m.Level
	}
	return NotifyRequest_INFO
}

func (m *NotifyRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *NotifyRequest) GetSource() *NotifyRequest_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *NotifyRequest) GetData() *NotifyRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type NotifyRequest_Source struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Program              string   `protobuf:"bytes,2,opt,name=program,proto3" json:"program,omitempty"`
	Instance             string   `protobuf:"bytes,3,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyRequest_Source) Reset()         { *m = NotifyRequest_Source{} }
func (m *NotifyRequest_Source) String() string { return proto.CompactTextString(m) }
func (*NotifyRequest_Source) ProtoMessage()    {}
func (*NotifyRequest_Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{0, 0}
}

func (m *NotifyRequest_Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRequest_Source.Unmarshal(m, b)
}
func (m *NotifyRequest_Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRequest_Source.Marshal(b, m, deterministic)
}
func (m *NotifyRequest_Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRequest_Source.Merge(m, src)
}
func (m *NotifyRequest_Source) XXX_Size() int {
	return xxx_messageInfo_NotifyRequest_Source.Size(m)
}
func (m *NotifyRequest_Source) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRequest_Source.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRequest_Source proto.InternalMessageInfo

func (m *NotifyRequest_Source) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NotifyRequest_Source) GetProgram() string {
	if m != nil {
		return m.Program
	}
	return ""
}

func (m *NotifyRequest_Source) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

type NotifyRequest_Data struct {
	DataEnc              NotifyRequest_Data_DataEnc `protobuf:"varint,1,opt,name=dataEnc,proto3,enum=luids.event.v1.NotifyRequest_Data_DataEnc" json:"dataEnc,omitempty"`
	Data                 []byte                     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *NotifyRequest_Data) Reset()         { *m = NotifyRequest_Data{} }
func (m *NotifyRequest_Data) String() string { return proto.CompactTextString(m) }
func (*NotifyRequest_Data) ProtoMessage()    {}
func (*NotifyRequest_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{0, 1}
}

func (m *NotifyRequest_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRequest_Data.Unmarshal(m, b)
}
func (m *NotifyRequest_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRequest_Data.Marshal(b, m, deterministic)
}
func (m *NotifyRequest_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRequest_Data.Merge(m, src)
}
func (m *NotifyRequest_Data) XXX_Size() int {
	return xxx_messageInfo_NotifyRequest_Data.Size(m)
}
func (m *NotifyRequest_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRequest_Data.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRequest_Data proto.InternalMessageInfo

func (m *NotifyRequest_Data) GetDataEnc() NotifyRequest_Data_DataEnc {
	if m != nil {
		return m.DataEnc
	}
	return NotifyRequest_Data_NODATA
}

func (m *NotifyRequest_Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type NotifyResponse struct {
	RequestID            string   `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyResponse) Reset()         { *m = NotifyResponse{} }
func (m *NotifyResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyResponse) ProtoMessage()    {}
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{1}
}

func (m *NotifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyResponse.Unmarshal(m, b)
}
func (m *NotifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyResponse.Marshal(b, m, deterministic)
}
func (m *NotifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyResponse.Merge(m, src)
}
func (m *NotifyResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyResponse.Size(m)
}
func (m *NotifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyResponse proto.InternalMessageInfo

func (m *NotifyResponse) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func init() {
	proto.RegisterEnum("luids.event.v1.NotifyRequest_Type", NotifyRequest_Type_name, NotifyRequest_Type_value)
	proto.RegisterEnum("luids.event.v1.NotifyRequest_Level", NotifyRequest_Level_name, NotifyRequest_Level_value)
	proto.RegisterEnum("luids.event.v1.NotifyRequest_Data_DataEnc", NotifyRequest_Data_DataEnc_name, NotifyRequest_Data_DataEnc_value)
	proto.RegisterType((*NotifyRequest)(nil), "luids.event.v1.NotifyRequest")
	proto.RegisterType((*NotifyRequest_Source)(nil), "luids.event.v1.NotifyRequest.Source")
	proto.RegisterType((*NotifyRequest_Data)(nil), "luids.event.v1.NotifyRequest.Data")
	proto.RegisterType((*NotifyResponse)(nil), "luids.event.v1.NotifyResponse")
}

func init() { proto.RegisterFile("notify.proto", fileDescriptor_aba76cc4ebe272d4) }

var fileDescriptor_aba76cc4ebe272d4 = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xdf, 0x8f, 0xd2, 0x4c,
	0x14, 0xa5, 0x50, 0x0a, 0xdc, 0x8f, 0x8f, 0x34, 0x13, 0x1f, 0x9a, 0xc6, 0x1f, 0xa4, 0xfa, 0x80,
	0x1a, 0xa7, 0x11, 0x13, 0xa3, 0xd1, 0x98, 0x20, 0xa0, 0x5b, 0xc3, 0x42, 0x32, 0xb0, 0x31, 0xee,
	0x5b, 0x69, 0x67, 0xbb, 0x4d, 0xda, 0x99, 0xda, 0x4e, 0x49, 0x78, 0xf4, 0xdd, 0x3f, 0xda, 0xcc,
	0x94, 0x82, 0xfb, 0x20, 0xfb, 0x32, 0xb9, 0x77, 0xe6, 0x9c, 0x73, 0xcf, 0xbd, 0x37, 0x03, 0x7d,
	0xc6, 0x45, 0x7c, 0xb3, 0xc7, 0x59, 0xce, 0x05, 0x47, 0x83, 0xa4, 0x8c, 0xc3, 0x02, 0xd3, 0x1d,
	0x65, 0x02, 0xef, 0x5e, 0xdb, 0x1f, 0xa2, 0x58, 0xdc, 0x96, 0x5b, 0x1c, 0xf0, 0xd4, 0x8d, 0x78,
	0xe2, 0xb3, 0xc8, 0x55, 0xc0, 0x6d, 0x79, 0xe3, 0x66, 0x62, 0x9f, 0xd1, 0xc2, 0x15, 0x71, 0x4a,
	0x0b, 0xe1, 0xa7, 0xd9, 0x29, 0xaa, 0xc4, 0x9c, 0xdf, 0x6d, 0xf8, 0x7f, 0xa9, 0xd4, 0x09, 0xfd,
	0x59, 0xd2, 0x42, 0xa0, 0x01, 0x34, 0xe3, 0xd0, 0xd2, 0x86, 0xda, 0xa8, 0x47, 0x9a, 0x71, 0x88,
	0xde, 0x82, 0x2e, 0x45, 0xac, 0xe6, 0x50, 0x1b, 0x0d, 0xc6, 0x0e, 0xbe, 0x5b, 0x1d, 0xdf, 0x21,
	0xe3, 0xcd, 0x3e, 0xa3, 0x44, 0xe1, 0x11, 0x02, 0x3d, 0xe0, 0x21, 0xb5, 0x5a, 0x43, 0x6d, 0xd4,
	0x26, 0x2a, 0x46, 0xef, 0xa1, 0x9d, 0xd0, 0x1d, 0x4d, 0x2c, 0x5d, 0x89, 0x3d, 0x3d, 0x2f, 0xb6,
	0x90, 0x50, 0x52, 0x31, 0xd0, 0x3b, 0xe8, 0x1d, 0xbd, 0x5b, 0xed, 0xa1, 0x36, 0xfa, 0x6f, 0x6c,
	0xe3, 0x88, 0xf3, 0x28, 0xa1, 0xb8, 0x6e, 0x17, 0x6f, 0x6a, 0x04, 0x39, 0x81, 0xd1, 0x47, 0x30,
	0x0a, 0x5e, 0xe6, 0x01, 0xb5, 0x0c, 0x45, 0x7b, 0x76, 0xbe, 0xea, 0x5a, 0x61, 0xc9, 0x81, 0x23,
	0xdb, 0x0f, 0x7d, 0xe1, 0x5b, 0x1d, 0xc5, 0xbd, 0xa7, 0xfd, 0x99, 0x2f, 0x7c, 0xa2, 0xf0, 0xf6,
	0x35, 0x18, 0x95, 0x12, 0xb2, 0xa1, 0x7b, 0xcb, 0x0b, 0xc1, 0xfc, 0x94, 0x1e, 0xc6, 0x7a, 0xcc,
	0x91, 0x05, 0x9d, 0x2c, 0xe7, 0x51, 0xee, 0xa7, 0x6a, 0xbe, 0x3d, 0x52, 0xa7, 0x92, 0x15, 0xb3,
	0x42, 0xf8, 0x2c, 0xa8, 0x46, 0xd8, 0x23, 0xc7, 0xdc, 0xfe, 0xa5, 0x81, 0x2e, 0x4b, 0xa1, 0x19,
	0x74, 0x64, 0xb1, 0x39, 0x0b, 0x94, 0xf2, 0x60, 0xfc, 0xe2, 0x7e, 0x7f, 0xea, 0x98, 0xb3, 0x80,
	0xd4, 0x54, 0xb9, 0x29, 0xd5, 0xa2, 0x74, 0xd0, 0xaf, 0xec, 0x3b, 0x4f, 0xa0, 0x73, 0xc0, 0x21,
	0x00, 0x63, 0xb9, 0x9a, 0x4d, 0x36, 0x13, 0xb3, 0x81, 0xba, 0xa0, 0x7f, 0x5b, 0xaf, 0x96, 0xa6,
	0xe6, 0x3c, 0x00, 0x5d, 0x2e, 0x1b, 0xf5, 0xa1, 0xbb, 0x9e, 0x4f, 0xaf, 0x88, 0xb7, 0xf9, 0x61,
	0x36, 0x9c, 0x4f, 0xd0, 0x56, 0x5b, 0x93, 0x40, 0x6f, 0xf9, 0x65, 0x65, 0x36, 0x50, 0x07, 0x5a,
	0x8b, 0xd5, 0x77, 0x53, 0x93, 0x3a, 0x97, 0xf3, 0x99, 0x77, 0x75, 0x69, 0x36, 0xe5, 0xf3, 0x85,
	0xf7, 0xf5, 0xc2, 0x6c, 0x49, 0xfe, 0x94, 0x78, 0x1b, 0x6f, 0x3a, 0x59, 0x98, 0xba, 0x83, 0x61,
	0x50, 0x3b, 0x2e, 0x32, 0xce, 0x0a, 0x8a, 0x1e, 0x42, 0x2f, 0xaf, 0xdc, 0x7b, 0xb3, 0xc3, 0xf8,
	0x4e, 0x17, 0xe3, 0x35, 0x18, 0x15, 0x1e, 0x79, 0xc7, 0xe8, 0xd1, 0xd9, 0x19, 0xd8, 0x8f, 0xff,
	0xf5, 0x5c, 0x15, 0x74, 0x1a, 0x9f, 0x5f, 0x5e, 0x3f, 0xff, 0xeb, 0x4b, 0x29, 0xf4, 0xab, 0x98,
	0xbb, 0x01, 0xcf, 0x69, 0xf5, 0xb3, 0x22, 0xca, 0x5c, 0x45, 0xcf, 0xb6, 0x5b, 0x43, 0xdd, 0xbc,
	0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xf2, 0xdc, 0x17, 0xa4, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotifyClient is the client API for Notify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotifyClient interface {
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
}

type notifyClient struct {
	cc *grpc.ClientConn
}

func NewNotifyClient(cc *grpc.ClientConn) NotifyClient {
	return &notifyClient{cc}
}

func (c *notifyClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, "/luids.event.v1.Notify/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServer is the server API for Notify service.
type NotifyServer interface {
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
}

// UnimplementedNotifyServer can be embedded to have forward compatible implementations.
type UnimplementedNotifyServer struct {
}

func (*UnimplementedNotifyServer) Notify(ctx context.Context, req *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}

func RegisterNotifyServer(s *grpc.Server, srv NotifyServer) {
	s.RegisterService(&_Notify_serviceDesc, srv)
}

func _Notify_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luids.event.v1.Notify/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notify_serviceDesc = grpc.ServiceDesc{
	ServiceName: "luids.event.v1.Notify",
	HandlerType: (*NotifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _Notify_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notify.proto",
}
