// Code generated by protoc-gen-go. DO NOT EDIT.
// source: classify.proto

package tlsutilpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClassifyConnectionRequest struct {
	Requests             []*ClassifyConnectionRequest_Request `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ClassifyConnectionRequest) Reset()         { *m = ClassifyConnectionRequest{} }
func (m *ClassifyConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ClassifyConnectionRequest) ProtoMessage()    {}
func (*ClassifyConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29fe88afc6e3cb8b, []int{0}
}

func (m *ClassifyConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassifyConnectionRequest.Unmarshal(m, b)
}
func (m *ClassifyConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassifyConnectionRequest.Marshal(b, m, deterministic)
}
func (m *ClassifyConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassifyConnectionRequest.Merge(m, src)
}
func (m *ClassifyConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_ClassifyConnectionRequest.Size(m)
}
func (m *ClassifyConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassifyConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClassifyConnectionRequest proto.InternalMessageInfo

func (m *ClassifyConnectionRequest) GetRequests() []*ClassifyConnectionRequest_Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type ClassifyConnectionRequest_Request struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Connection           *ConnectionData `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ClassifyConnectionRequest_Request) Reset()         { *m = ClassifyConnectionRequest_Request{} }
func (m *ClassifyConnectionRequest_Request) String() string { return proto.CompactTextString(m) }
func (*ClassifyConnectionRequest_Request) ProtoMessage()    {}
func (*ClassifyConnectionRequest_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_29fe88afc6e3cb8b, []int{0, 0}
}

func (m *ClassifyConnectionRequest_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassifyConnectionRequest_Request.Unmarshal(m, b)
}
func (m *ClassifyConnectionRequest_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassifyConnectionRequest_Request.Marshal(b, m, deterministic)
}
func (m *ClassifyConnectionRequest_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassifyConnectionRequest_Request.Merge(m, src)
}
func (m *ClassifyConnectionRequest_Request) XXX_Size() int {
	return xxx_messageInfo_ClassifyConnectionRequest_Request.Size(m)
}
func (m *ClassifyConnectionRequest_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassifyConnectionRequest_Request.DiscardUnknown(m)
}

var xxx_messageInfo_ClassifyConnectionRequest_Request proto.InternalMessageInfo

func (m *ClassifyConnectionRequest_Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClassifyConnectionRequest_Request) GetConnection() *ConnectionData {
	if m != nil {
		return m.Connection
	}
	return nil
}

type ClassifyConnectionResponse struct {
	Responses            []*ClassifyConnectionResponse_Response `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *ClassifyConnectionResponse) Reset()         { *m = ClassifyConnectionResponse{} }
func (m *ClassifyConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*ClassifyConnectionResponse) ProtoMessage()    {}
func (*ClassifyConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29fe88afc6e3cb8b, []int{1}
}

func (m *ClassifyConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassifyConnectionResponse.Unmarshal(m, b)
}
func (m *ClassifyConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassifyConnectionResponse.Marshal(b, m, deterministic)
}
func (m *ClassifyConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassifyConnectionResponse.Merge(m, src)
}
func (m *ClassifyConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_ClassifyConnectionResponse.Size(m)
}
func (m *ClassifyConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassifyConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClassifyConnectionResponse proto.InternalMessageInfo

func (m *ClassifyConnectionResponse) GetResponses() []*ClassifyConnectionResponse_Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

type ClassifyConnectionResponse_Response struct {
	Id                   string                                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Results              []*ClassifyConnectionResponse_Response_Result `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Err                  string                                        `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *ClassifyConnectionResponse_Response) Reset()         { *m = ClassifyConnectionResponse_Response{} }
func (m *ClassifyConnectionResponse_Response) String() string { return proto.CompactTextString(m) }
func (*ClassifyConnectionResponse_Response) ProtoMessage()    {}
func (*ClassifyConnectionResponse_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_29fe88afc6e3cb8b, []int{1, 0}
}

func (m *ClassifyConnectionResponse_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassifyConnectionResponse_Response.Unmarshal(m, b)
}
func (m *ClassifyConnectionResponse_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassifyConnectionResponse_Response.Marshal(b, m, deterministic)
}
func (m *ClassifyConnectionResponse_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassifyConnectionResponse_Response.Merge(m, src)
}
func (m *ClassifyConnectionResponse_Response) XXX_Size() int {
	return xxx_messageInfo_ClassifyConnectionResponse_Response.Size(m)
}
func (m *ClassifyConnectionResponse_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassifyConnectionResponse_Response.DiscardUnknown(m)
}

var xxx_messageInfo_ClassifyConnectionResponse_Response proto.InternalMessageInfo

func (m *ClassifyConnectionResponse_Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClassifyConnectionResponse_Response) GetResults() []*ClassifyConnectionResponse_Response_Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ClassifyConnectionResponse_Response) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ClassifyConnectionResponse_Response_Result struct {
	Label                string   `protobuf:"bytes,1,opt,name=Label,json=label,proto3" json:"Label,omitempty"`
	Prob                 float32  `protobuf:"fixed32,2,opt,name=prob,proto3" json:"prob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClassifyConnectionResponse_Response_Result) Reset() {
	*m = ClassifyConnectionResponse_Response_Result{}
}
func (m *ClassifyConnectionResponse_Response_Result) String() string {
	return proto.CompactTextString(m)
}
func (*ClassifyConnectionResponse_Response_Result) ProtoMessage() {}
func (*ClassifyConnectionResponse_Response_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_29fe88afc6e3cb8b, []int{1, 0, 0}
}

func (m *ClassifyConnectionResponse_Response_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassifyConnectionResponse_Response_Result.Unmarshal(m, b)
}
func (m *ClassifyConnectionResponse_Response_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassifyConnectionResponse_Response_Result.Marshal(b, m, deterministic)
}
func (m *ClassifyConnectionResponse_Response_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassifyConnectionResponse_Response_Result.Merge(m, src)
}
func (m *ClassifyConnectionResponse_Response_Result) XXX_Size() int {
	return xxx_messageInfo_ClassifyConnectionResponse_Response_Result.Size(m)
}
func (m *ClassifyConnectionResponse_Response_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassifyConnectionResponse_Response_Result.DiscardUnknown(m)
}

var xxx_messageInfo_ClassifyConnectionResponse_Response_Result proto.InternalMessageInfo

func (m *ClassifyConnectionResponse_Response_Result) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *ClassifyConnectionResponse_Response_Result) GetProb() float32 {
	if m != nil {
		return m.Prob
	}
	return 0
}

func init() {
	proto.RegisterType((*ClassifyConnectionRequest)(nil), "luids.tlsutil.v1.ClassifyConnectionRequest")
	proto.RegisterType((*ClassifyConnectionRequest_Request)(nil), "luids.tlsutil.v1.ClassifyConnectionRequest.Request")
	proto.RegisterType((*ClassifyConnectionResponse)(nil), "luids.tlsutil.v1.ClassifyConnectionResponse")
	proto.RegisterType((*ClassifyConnectionResponse_Response)(nil), "luids.tlsutil.v1.ClassifyConnectionResponse.Response")
	proto.RegisterType((*ClassifyConnectionResponse_Response_Result)(nil), "luids.tlsutil.v1.ClassifyConnectionResponse.Response.Result")
}

func init() { proto.RegisterFile("classify.proto", fileDescriptor_29fe88afc6e3cb8b) }

var fileDescriptor_29fe88afc6e3cb8b = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x6d, 0xe7, 0xfe, 0xbd, 0x83, 0x31, 0x82, 0x87, 0xda, 0x53, 0xd9, 0x69, 0x30, 0x97,
	0x62, 0x87, 0x37, 0x0f, 0xe2, 0x3c, 0x0a, 0x42, 0x04, 0x0f, 0x7a, 0x6a, 0xbb, 0x38, 0x23, 0x59,
	0x53, 0x93, 0x74, 0xe0, 0x77, 0xf2, 0x03, 0xf8, 0x15, 0xfc, 0x56, 0xb2, 0xb4, 0xe9, 0x64, 0x54,
	0x70, 0x9e, 0xfa, 0xb4, 0x7d, 0xdf, 0xe7, 0xf7, 0x3e, 0xc9, 0x0b, 0xc3, 0x94, 0xc7, 0x4a, 0xb1,
	0xe7, 0x77, 0x9c, 0x4b, 0xa1, 0x05, 0x1a, 0xf1, 0x82, 0x2d, 0x15, 0xd6, 0x5c, 0x15, 0x9a, 0x71,
	0xbc, 0x39, 0xf7, 0x67, 0x2b, 0xa6, 0x5f, 0x8a, 0x04, 0xa7, 0x62, 0x1d, 0x9a, 0x9f, 0x33, 0x26,
	0xc2, 0x38, 0x67, 0x2a, 0xac, 0x8a, 0xc2, 0x54, 0xac, 0xd7, 0x22, 0x2b, 0x0d, 0xc6, 0x5f, 0x0e,
	0x9c, 0x2e, 0x2a, 0xcf, 0x85, 0xc8, 0x32, 0x9a, 0x6a, 0x26, 0x32, 0x42, 0xdf, 0x0a, 0xaa, 0x34,
	0xba, 0x83, 0x9e, 0x2c, 0xa5, 0xf2, 0x9c, 0xa0, 0x35, 0x19, 0x44, 0x73, 0xbc, 0x4f, 0xc4, 0xbf,
	0xb6, 0xe3, 0xea, 0x49, 0x6a, 0x13, 0xff, 0x09, 0xba, 0xd6, 0x7b, 0x08, 0x2e, 0x5b, 0x7a, 0x4e,
	0xe0, 0x4c, 0xfa, 0xc4, 0x65, 0x4b, 0x74, 0x05, 0x90, 0xd6, 0x0e, 0x9e, 0x1b, 0x38, 0x93, 0x41,
	0x14, 0x34, 0xd0, 0xea, 0x9a, 0x9b, 0x58, 0xc7, 0xe4, 0x47, 0xcf, 0xf8, 0xc3, 0x05, 0xbf, 0x69,
	0x18, 0x95, 0x8b, 0x4c, 0x51, 0x74, 0x0f, 0x7d, 0x59, 0x69, 0x9b, 0xe6, 0xe2, 0x6f, 0x69, 0xca,
	0x26, 0x6c, 0x05, 0xd9, 0xf9, 0xf8, 0x9f, 0x0e, 0xf4, 0x6a, 0xc2, 0x7e, 0xa4, 0x07, 0xe8, 0x4a,
	0xaa, 0x0a, 0xae, 0x95, 0xe7, 0x1a, 0xde, 0xe5, 0xbf, 0x78, 0x5b, 0x51, 0x70, 0x4d, 0xac, 0x19,
	0x1a, 0x41, 0x8b, 0x4a, 0xe9, 0xb5, 0x0c, 0x68, 0x2b, 0xfd, 0x08, 0x3a, 0x65, 0x11, 0x3a, 0x81,
	0xf6, 0x6d, 0x9c, 0x50, 0x5e, 0x8d, 0xd1, 0xe6, 0xdb, 0x17, 0x84, 0xe0, 0x38, 0x97, 0x22, 0x31,
	0xc7, 0xea, 0x12, 0xa3, 0xa3, 0x0d, 0xf4, 0x2c, 0x1c, 0xbd, 0xc2, 0x60, 0x37, 0x80, 0x42, 0xd3,
	0x03, 0x6e, 0xd9, 0x3f, 0x3b, 0x24, 0xd4, 0xf8, 0xe8, 0x7a, 0xf6, 0x38, 0x6d, 0xda, 0xd1, 0x54,
	0x48, 0x1a, 0x9a, 0xa5, 0x5c, 0xd1, 0xcc, 0x2e, 0x6b, 0x9e, 0x24, 0x1d, 0xf3, 0x6d, 0xfe, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x38, 0xb8, 0xe6, 0xad, 0xfb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClassifyClient is the client API for Classify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClassifyClient interface {
	Connections(ctx context.Context, in *ClassifyConnectionRequest, opts ...grpc.CallOption) (*ClassifyConnectionResponse, error)
}

type classifyClient struct {
	cc *grpc.ClientConn
}

func NewClassifyClient(cc *grpc.ClientConn) ClassifyClient {
	return &classifyClient{cc}
}

func (c *classifyClient) Connections(ctx context.Context, in *ClassifyConnectionRequest, opts ...grpc.CallOption) (*ClassifyConnectionResponse, error) {
	out := new(ClassifyConnectionResponse)
	err := c.cc.Invoke(ctx, "/luids.tlsutil.v1.Classify/Connections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassifyServer is the server API for Classify service.
type ClassifyServer interface {
	Connections(context.Context, *ClassifyConnectionRequest) (*ClassifyConnectionResponse, error)
}

// UnimplementedClassifyServer can be embedded to have forward compatible implementations.
type UnimplementedClassifyServer struct {
}

func (*UnimplementedClassifyServer) Connections(ctx context.Context, req *ClassifyConnectionRequest) (*ClassifyConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connections not implemented")
}

func RegisterClassifyServer(s *grpc.Server, srv ClassifyServer) {
	s.RegisterService(&_Classify_serviceDesc, srv)
}

func _Classify_Connections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifyServer).Connections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luids.tlsutil.v1.Classify/Connections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifyServer).Connections(ctx, req.(*ClassifyConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Classify_serviceDesc = grpc.ServiceDesc{
	ServiceName: "luids.tlsutil.v1.Classify",
	HandlerType: (*ClassifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connections",
			Handler:    _Classify_Connections_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classify.proto",
}
