// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package tlsutilpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CertificateData struct {
	Digest               string   `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Raw                  []byte   `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertificateData) Reset()         { *m = CertificateData{} }
func (m *CertificateData) String() string { return proto.CompactTextString(m) }
func (*CertificateData) ProtoMessage()    {}
func (*CertificateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *CertificateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateData.Unmarshal(m, b)
}
func (m *CertificateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateData.Marshal(b, m, deterministic)
}
func (m *CertificateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateData.Merge(m, src)
}
func (m *CertificateData) XXX_Size() int {
	return xxx_messageInfo_CertificateData.Size(m)
}
func (m *CertificateData) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateData.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateData proto.InternalMessageInfo

func (m *CertificateData) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *CertificateData) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type RecordData struct {
	StreamId             string               `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 int32                `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Len                  int32                `protobuf:"varint,4,opt,name=len,proto3" json:"len,omitempty"`
	Ciphered             bool                 `protobuf:"varint,5,opt,name=ciphered,proto3" json:"ciphered,omitempty"`
	Fragmented           bool                 `protobuf:"varint,6,opt,name=fragmented,proto3" json:"fragmented,omitempty"`
	MsgsCount            int32                `protobuf:"varint,7,opt,name=msgs_count,json=msgsCount,proto3" json:"msgs_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecordData) Reset()         { *m = RecordData{} }
func (m *RecordData) String() string { return proto.CompactTextString(m) }
func (*RecordData) ProtoMessage()    {}
func (*RecordData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *RecordData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordData.Unmarshal(m, b)
}
func (m *RecordData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordData.Marshal(b, m, deterministic)
}
func (m *RecordData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordData.Merge(m, src)
}
func (m *RecordData) XXX_Size() int {
	return xxx_messageInfo_RecordData.Size(m)
}
func (m *RecordData) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordData.DiscardUnknown(m)
}

var xxx_messageInfo_RecordData proto.InternalMessageInfo

func (m *RecordData) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

func (m *RecordData) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *RecordData) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RecordData) GetLen() int32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *RecordData) GetCiphered() bool {
	if m != nil {
		return m.Ciphered
	}
	return false
}

func (m *RecordData) GetFragmented() bool {
	if m != nil {
		return m.Fragmented
	}
	return false
}

func (m *RecordData) GetMsgsCount() int32 {
	if m != nil {
		return m.MsgsCount
	}
	return 0
}

type ConnectionData struct {
	Id                   string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Info                 *ConnectionData_ConnectionInfo  `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	SendStream           *ConnectionData_StreamData      `protobuf:"bytes,3,opt,name=send_stream,json=sendStream,proto3" json:"send_stream,omitempty"`
	RcvdStream           *ConnectionData_StreamData      `protobuf:"bytes,4,opt,name=rcvd_stream,json=rcvdStream,proto3" json:"rcvd_stream,omitempty"`
	ClientHello          *ConnectionData_ClientHelloData `protobuf:"bytes,5,opt,name=client_hello,json=clientHello,proto3" json:"client_hello,omitempty"`
	ServerHello          *ConnectionData_ServerHelloData `protobuf:"bytes,6,opt,name=server_hello,json=serverHello,proto3" json:"server_hello,omitempty"`
	ClientCerts          []*ConnectionData_CertSummary   `protobuf:"bytes,7,rep,name=client_certs,json=clientCerts,proto3" json:"client_certs,omitempty"`
	ServerCerts          []*ConnectionData_CertSummary   `protobuf:"bytes,8,rep,name=server_certs,json=serverCerts,proto3" json:"server_certs,omitempty"`
	Tags                 []string                        `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ConnectionData) Reset()         { *m = ConnectionData{} }
func (m *ConnectionData) String() string { return proto.CompactTextString(m) }
func (*ConnectionData) ProtoMessage()    {}
func (*ConnectionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *ConnectionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionData.Unmarshal(m, b)
}
func (m *ConnectionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionData.Marshal(b, m, deterministic)
}
func (m *ConnectionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionData.Merge(m, src)
}
func (m *ConnectionData) XXX_Size() int {
	return xxx_messageInfo_ConnectionData.Size(m)
}
func (m *ConnectionData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionData.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionData proto.InternalMessageInfo

func (m *ConnectionData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConnectionData) GetInfo() *ConnectionData_ConnectionInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConnectionData) GetSendStream() *ConnectionData_StreamData {
	if m != nil {
		return m.SendStream
	}
	return nil
}

func (m *ConnectionData) GetRcvdStream() *ConnectionData_StreamData {
	if m != nil {
		return m.RcvdStream
	}
	return nil
}

func (m *ConnectionData) GetClientHello() *ConnectionData_ClientHelloData {
	if m != nil {
		return m.ClientHello
	}
	return nil
}

func (m *ConnectionData) GetServerHello() *ConnectionData_ServerHelloData {
	if m != nil {
		return m.ServerHello
	}
	return nil
}

func (m *ConnectionData) GetClientCerts() []*ConnectionData_CertSummary {
	if m != nil {
		return m.ClientCerts
	}
	return nil
}

func (m *ConnectionData) GetServerCerts() []*ConnectionData_CertSummary {
	if m != nil {
		return m.ServerCerts
	}
	return nil
}

func (m *ConnectionData) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ConnectionData_ConnectionInfo struct {
	Start                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	DurationNsecs        int64                `protobuf:"varint,3,opt,name=duration_nsecs,json=durationNsecs,proto3" json:"duration_nsecs,omitempty"`
	ClientIp             string               `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ServerIp             string               `protobuf:"bytes,5,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	ClientPort           uint32               `protobuf:"varint,6,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	ServerPort           uint32               `protobuf:"varint,7,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	Uncompleted          bool                 `protobuf:"varint,8,opt,name=uncompleted,proto3" json:"uncompleted,omitempty"`
	DetectedError        bool                 `protobuf:"varint,9,opt,name=detected_error,json=detectedError,proto3" json:"detected_error,omitempty"`
	CompletedHandshake   bool                 `protobuf:"varint,10,opt,name=completed_handshake,json=completedHandshake,proto3" json:"completed_handshake,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConnectionData_ConnectionInfo) Reset()         { *m = ConnectionData_ConnectionInfo{} }
func (m *ConnectionData_ConnectionInfo) String() string { return proto.CompactTextString(m) }
func (*ConnectionData_ConnectionInfo) ProtoMessage()    {}
func (*ConnectionData_ConnectionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 0}
}

func (m *ConnectionData_ConnectionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionData_ConnectionInfo.Unmarshal(m, b)
}
func (m *ConnectionData_ConnectionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionData_ConnectionInfo.Marshal(b, m, deterministic)
}
func (m *ConnectionData_ConnectionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionData_ConnectionInfo.Merge(m, src)
}
func (m *ConnectionData_ConnectionInfo) XXX_Size() int {
	return xxx_messageInfo_ConnectionData_ConnectionInfo.Size(m)
}
func (m *ConnectionData_ConnectionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionData_ConnectionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionData_ConnectionInfo proto.InternalMessageInfo

func (m *ConnectionData_ConnectionInfo) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *ConnectionData_ConnectionInfo) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *ConnectionData_ConnectionInfo) GetDurationNsecs() int64 {
	if m != nil {
		return m.DurationNsecs
	}
	return 0
}

func (m *ConnectionData_ConnectionInfo) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *ConnectionData_ConnectionInfo) GetServerIp() string {
	if m != nil {
		return m.ServerIp
	}
	return ""
}

func (m *ConnectionData_ConnectionInfo) GetClientPort() uint32 {
	if m != nil {
		return m.ClientPort
	}
	return 0
}

func (m *ConnectionData_ConnectionInfo) GetServerPort() uint32 {
	if m != nil {
		return m.ServerPort
	}
	return 0
}

func (m *ConnectionData_ConnectionInfo) GetUncompleted() bool {
	if m != nil {
		return m.Uncompleted
	}
	return false
}

func (m *ConnectionData_ConnectionInfo) GetDetectedError() bool {
	if m != nil {
		return m.DetectedError
	}
	return false
}

func (m *ConnectionData_ConnectionInfo) GetCompletedHandshake() bool {
	if m != nil {
		return m.CompletedHandshake
	}
	return false
}

type ConnectionData_StreamData struct {
	Id                   string                                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Info                 *ConnectionData_StreamData_StreamInfo        `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	PlaintextAcc         *ConnectionData_StreamData_PlaintextSummary  `protobuf:"bytes,3,opt,name=plaintext_acc,json=plaintextAcc,proto3" json:"plaintext_acc,omitempty"`
	CiphertextAcc        *ConnectionData_StreamData_CiphertextSummary `protobuf:"bytes,4,opt,name=ciphertext_acc,json=ciphertextAcc,proto3" json:"ciphertext_acc,omitempty"`
	Handshakes           []*ConnectionData_StreamData_HandshakeItem   `protobuf:"bytes,5,rep,name=handshakes,proto3" json:"handshakes,omitempty"`
	HandshakeSum         int32                                        `protobuf:"varint,6,opt,name=handshake_sum,json=handshakeSum,proto3" json:"handshake_sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *ConnectionData_StreamData) Reset()         { *m = ConnectionData_StreamData{} }
func (m *ConnectionData_StreamData) String() string { return proto.CompactTextString(m) }
func (*ConnectionData_StreamData) ProtoMessage()    {}
func (*ConnectionData_StreamData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 1}
}

func (m *ConnectionData_StreamData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionData_StreamData.Unmarshal(m, b)
}
func (m *ConnectionData_StreamData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionData_StreamData.Marshal(b, m, deterministic)
}
func (m *ConnectionData_StreamData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionData_StreamData.Merge(m, src)
}
func (m *ConnectionData_StreamData) XXX_Size() int {
	return xxx_messageInfo_ConnectionData_StreamData.Size(m)
}
func (m *ConnectionData_StreamData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionData_StreamData.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionData_StreamData proto.InternalMessageInfo

func (m *ConnectionData_StreamData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConnectionData_StreamData) GetInfo() *ConnectionData_StreamData_StreamInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConnectionData_StreamData) GetPlaintextAcc() *ConnectionData_StreamData_PlaintextSummary {
	if m != nil {
		return m.PlaintextAcc
	}
	return nil
}

func (m *ConnectionData_StreamData) GetCiphertextAcc() *ConnectionData_StreamData_CiphertextSummary {
	if m != nil {
		return m.CiphertextAcc
	}
	return nil
}

func (m *ConnectionData_StreamData) GetHandshakes() []*ConnectionData_StreamData_HandshakeItem {
	if m != nil {
		return m.Handshakes
	}
	return nil
}

func (m *ConnectionData_StreamData) GetHandshakeSum() int32 {
	if m != nil {
		return m.HandshakeSum
	}
	return 0
}

type ConnectionData_StreamData_StreamInfo struct {
	Start                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	DurationNsecs        int64                `protobuf:"varint,3,opt,name=duration_nsecs,json=durationNsecs,proto3" json:"duration_nsecs,omitempty"`
	SawStart             bool                 `protobuf:"varint,4,opt,name=saw_start,json=sawStart,proto3" json:"saw_start,omitempty"`
	SawEnd               bool                 `protobuf:"varint,5,opt,name=saw_end,json=sawEnd,proto3" json:"saw_end,omitempty"`
	SrcIp                string               `protobuf:"bytes,6,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp                string               `protobuf:"bytes,7,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort              uint32               `protobuf:"varint,8,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort              uint32               `protobuf:"varint,9,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Bytes                int64                `protobuf:"varint,10,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Packets              int64                `protobuf:"varint,11,opt,name=packets,proto3" json:"packets,omitempty"`
	Bps                  float32              `protobuf:"fixed32,12,opt,name=bps,proto3" json:"bps,omitempty"`
	Pps                  float32              `protobuf:"fixed32,13,opt,name=pps,proto3" json:"pps,omitempty"`
	DetectedError        bool                 `protobuf:"varint,14,opt,name=detected_error,json=detectedError,proto3" json:"detected_error,omitempty"`
	ErrorType            string               `protobuf:"bytes,15,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	ErrorTime            *timestamp.Timestamp `protobuf:"bytes,16,opt,name=error_time,json=errorTime,proto3" json:"error_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConnectionData_StreamData_StreamInfo) Reset()         { *m = ConnectionData_StreamData_StreamInfo{} }
func (m *ConnectionData_StreamData_StreamInfo) String() string { return proto.CompactTextString(m) }
func (*ConnectionData_StreamData_StreamInfo) ProtoMessage()    {}
func (*ConnectionData_StreamData_StreamInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 1, 0}
}

func (m *ConnectionData_StreamData_StreamInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionData_StreamData_StreamInfo.Unmarshal(m, b)
}
func (m *ConnectionData_StreamData_StreamInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionData_StreamData_StreamInfo.Marshal(b, m, deterministic)
}
func (m *ConnectionData_StreamData_StreamInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionData_StreamData_StreamInfo.Merge(m, src)
}
func (m *ConnectionData_StreamData_StreamInfo) XXX_Size() int {
	return xxx_messageInfo_ConnectionData_StreamData_StreamInfo.Size(m)
}
func (m *ConnectionData_StreamData_StreamInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionData_StreamData_StreamInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionData_StreamData_StreamInfo proto.InternalMessageInfo

func (m *ConnectionData_StreamData_StreamInfo) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *ConnectionData_StreamData_StreamInfo) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *ConnectionData_StreamData_StreamInfo) GetDurationNsecs() int64 {
	if m != nil {
		return m.DurationNsecs
	}
	return 0
}

func (m *ConnectionData_StreamData_StreamInfo) GetSawStart() bool {
	if m != nil {
		return m.SawStart
	}
	return false
}

func (m *ConnectionData_StreamData_StreamInfo) GetSawEnd() bool {
	if m != nil {
		return m.SawEnd
	}
	return false
}

func (m *ConnectionData_StreamData_StreamInfo) GetSrcIp() string {
	if m != nil {
		return m.SrcIp
	}
	return ""
}

func (m *ConnectionData_StreamData_StreamInfo) GetDstIp() string {
	if m != nil {
		return m.DstIp
	}
	return ""
}

func (m *ConnectionData_StreamData_StreamInfo) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *ConnectionData_StreamData_StreamInfo) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

func (m *ConnectionData_StreamData_StreamInfo) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *ConnectionData_StreamData_StreamInfo) GetPackets() int64 {
	if m != nil {
		return m.Packets
	}
	return 0
}

func (m *ConnectionData_StreamData_StreamInfo) GetBps() float32 {
	if m != nil {
		return m.Bps
	}
	return 0
}

func (m *ConnectionData_StreamData_StreamInfo) GetPps() float32 {
	if m != nil {
		return m.Pps
	}
	return 0
}

func (m *ConnectionData_StreamData_StreamInfo) GetDetectedError() bool {
	if m != nil {
		return m.DetectedError
	}
	return false
}

func (m *ConnectionData_StreamData_StreamInfo) GetErrorType() string {
	if m != nil {
		return m.ErrorType
	}
	return ""
}

func (m *ConnectionData_StreamData_StreamInfo) GetErrorTime() *timestamp.Timestamp {
	if m != nil {
		return m.ErrorTime
	}
	return nil
}

type ConnectionData_StreamData_PlaintextSummary struct {
	HskRecords           int64    `protobuf:"varint,1,opt,name=hsk_records,json=hskRecords,proto3" json:"hsk_records,omitempty"`
	HskBytes             int64    `protobuf:"varint,2,opt,name=hsk_bytes,json=hskBytes,proto3" json:"hsk_bytes,omitempty"`
	AlertRecords         int64    `protobuf:"varint,3,opt,name=alert_records,json=alertRecords,proto3" json:"alert_records,omitempty"`
	AlertBytes           int64    `protobuf:"varint,4,opt,name=alert_bytes,json=alertBytes,proto3" json:"alert_bytes,omitempty"`
	CctRecords           int64    `protobuf:"varint,5,opt,name=cct_records,json=cctRecords,proto3" json:"cct_records,omitempty"`
	CctBytes             int64    `protobuf:"varint,6,opt,name=cct_bytes,json=cctBytes,proto3" json:"cct_bytes,omitempty"`
	AppdataRecords       int64    `protobuf:"varint,7,opt,name=appdata_records,json=appdataRecords,proto3" json:"appdata_records,omitempty"`
	AppdataBytes         int64    `protobuf:"varint,8,opt,name=appdata_bytes,json=appdataBytes,proto3" json:"appdata_bytes,omitempty"`
	FragmentedRecords    int32    `protobuf:"varint,9,opt,name=fragmented_records,json=fragmentedRecords,proto3" json:"fragmented_records,omitempty"`
	MaxMessages          int32    `protobuf:"varint,10,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionData_StreamData_PlaintextSummary) Reset() {
	*m = ConnectionData_StreamData_PlaintextSummary{}
}
func (m *ConnectionData_StreamData_PlaintextSummary) String() string {
	return proto.CompactTextString(m)
}
func (*ConnectionData_StreamData_PlaintextSummary) ProtoMessage() {}
func (*ConnectionData_StreamData_PlaintextSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 1, 1}
}

func (m *ConnectionData_StreamData_PlaintextSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionData_StreamData_PlaintextSummary.Unmarshal(m, b)
}
func (m *ConnectionData_StreamData_PlaintextSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionData_StreamData_PlaintextSummary.Marshal(b, m, deterministic)
}
func (m *ConnectionData_StreamData_PlaintextSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionData_StreamData_PlaintextSummary.Merge(m, src)
}
func (m *ConnectionData_StreamData_PlaintextSummary) XXX_Size() int {
	return xxx_messageInfo_ConnectionData_StreamData_PlaintextSummary.Size(m)
}
func (m *ConnectionData_StreamData_PlaintextSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionData_StreamData_PlaintextSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionData_StreamData_PlaintextSummary proto.InternalMessageInfo

func (m *ConnectionData_StreamData_PlaintextSummary) GetHskRecords() int64 {
	if m != nil {
		return m.HskRecords
	}
	return 0
}

func (m *ConnectionData_StreamData_PlaintextSummary) GetHskBytes() int64 {
	if m != nil {
		return m.HskBytes
	}
	return 0
}

func (m *ConnectionData_StreamData_PlaintextSummary) GetAlertRecords() int64 {
	if m != nil {
		return m.AlertRecords
	}
	return 0
}

func (m *ConnectionData_StreamData_PlaintextSummary) GetAlertBytes() int64 {
	if m != nil {
		return m.AlertBytes
	}
	return 0
}

func (m *ConnectionData_StreamData_PlaintextSummary) GetCctRecords() int64 {
	if m != nil {
		return m.CctRecords
	}
	return 0
}

func (m *ConnectionData_StreamData_PlaintextSummary) GetCctBytes() int64 {
	if m != nil {
		return m.CctBytes
	}
	return 0
}

func (m *ConnectionData_StreamData_PlaintextSummary) GetAppdataRecords() int64 {
	if m != nil {
		return m.AppdataRecords
	}
	return 0
}

func (m *ConnectionData_StreamData_PlaintextSummary) GetAppdataBytes() int64 {
	if m != nil {
		return m.AppdataBytes
	}
	return 0
}

func (m *ConnectionData_StreamData_PlaintextSummary) GetFragmentedRecords() int32 {
	if m != nil {
		return m.FragmentedRecords
	}
	return 0
}

func (m *ConnectionData_StreamData_PlaintextSummary) GetMaxMessages() int32 {
	if m != nil {
		return m.MaxMessages
	}
	return 0
}

type ConnectionData_StreamData_CiphertextSummary struct {
	HskRecords           int64    `protobuf:"varint,1,opt,name=hsk_records,json=hskRecords,proto3" json:"hsk_records,omitempty"`
	HskBytes             int64    `protobuf:"varint,2,opt,name=hsk_bytes,json=hskBytes,proto3" json:"hsk_bytes,omitempty"`
	AlertRecords         int64    `protobuf:"varint,3,opt,name=alert_records,json=alertRecords,proto3" json:"alert_records,omitempty"`
	AlertBytes           int64    `protobuf:"varint,4,opt,name=alert_bytes,json=alertBytes,proto3" json:"alert_bytes,omitempty"`
	CctRecords           int64    `protobuf:"varint,5,opt,name=cct_records,json=cctRecords,proto3" json:"cct_records,omitempty"`
	CctBytes             int64    `protobuf:"varint,6,opt,name=cct_bytes,json=cctBytes,proto3" json:"cct_bytes,omitempty"`
	AppdataRecords       int64    `protobuf:"varint,7,opt,name=appdata_records,json=appdataRecords,proto3" json:"appdata_records,omitempty"`
	AppdataBytes         int64    `protobuf:"varint,8,opt,name=appdata_bytes,json=appdataBytes,proto3" json:"appdata_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionData_StreamData_CiphertextSummary) Reset() {
	*m = ConnectionData_StreamData_CiphertextSummary{}
}
func (m *ConnectionData_StreamData_CiphertextSummary) String() string {
	return proto.CompactTextString(m)
}
func (*ConnectionData_StreamData_CiphertextSummary) ProtoMessage() {}
func (*ConnectionData_StreamData_CiphertextSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 1, 2}
}

func (m *ConnectionData_StreamData_CiphertextSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionData_StreamData_CiphertextSummary.Unmarshal(m, b)
}
func (m *ConnectionData_StreamData_CiphertextSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionData_StreamData_CiphertextSummary.Marshal(b, m, deterministic)
}
func (m *ConnectionData_StreamData_CiphertextSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionData_StreamData_CiphertextSummary.Merge(m, src)
}
func (m *ConnectionData_StreamData_CiphertextSummary) XXX_Size() int {
	return xxx_messageInfo_ConnectionData_StreamData_CiphertextSummary.Size(m)
}
func (m *ConnectionData_StreamData_CiphertextSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionData_StreamData_CiphertextSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionData_StreamData_CiphertextSummary proto.InternalMessageInfo

func (m *ConnectionData_StreamData_CiphertextSummary) GetHskRecords() int64 {
	if m != nil {
		return m.HskRecords
	}
	return 0
}

func (m *ConnectionData_StreamData_CiphertextSummary) GetHskBytes() int64 {
	if m != nil {
		return m.HskBytes
	}
	return 0
}

func (m *ConnectionData_StreamData_CiphertextSummary) GetAlertRecords() int64 {
	if m != nil {
		return m.AlertRecords
	}
	return 0
}

func (m *ConnectionData_StreamData_CiphertextSummary) GetAlertBytes() int64 {
	if m != nil {
		return m.AlertBytes
	}
	return 0
}

func (m *ConnectionData_StreamData_CiphertextSummary) GetCctRecords() int64 {
	if m != nil {
		return m.CctRecords
	}
	return 0
}

func (m *ConnectionData_StreamData_CiphertextSummary) GetCctBytes() int64 {
	if m != nil {
		return m.CctBytes
	}
	return 0
}

func (m *ConnectionData_StreamData_CiphertextSummary) GetAppdataRecords() int64 {
	if m != nil {
		return m.AppdataRecords
	}
	return 0
}

func (m *ConnectionData_StreamData_CiphertextSummary) GetAppdataBytes() int64 {
	if m != nil {
		return m.AppdataBytes
	}
	return 0
}

type ConnectionData_StreamData_HandshakeItem struct {
	Htype                uint32   `protobuf:"varint,1,opt,name=htype,proto3" json:"htype,omitempty"`
	Len                  uint32   `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionData_StreamData_HandshakeItem) Reset() {
	*m = ConnectionData_StreamData_HandshakeItem{}
}
func (m *ConnectionData_StreamData_HandshakeItem) String() string { return proto.CompactTextString(m) }
func (*ConnectionData_StreamData_HandshakeItem) ProtoMessage()    {}
func (*ConnectionData_StreamData_HandshakeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 1, 3}
}

func (m *ConnectionData_StreamData_HandshakeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionData_StreamData_HandshakeItem.Unmarshal(m, b)
}
func (m *ConnectionData_StreamData_HandshakeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionData_StreamData_HandshakeItem.Marshal(b, m, deterministic)
}
func (m *ConnectionData_StreamData_HandshakeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionData_StreamData_HandshakeItem.Merge(m, src)
}
func (m *ConnectionData_StreamData_HandshakeItem) XXX_Size() int {
	return xxx_messageInfo_ConnectionData_StreamData_HandshakeItem.Size(m)
}
func (m *ConnectionData_StreamData_HandshakeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionData_StreamData_HandshakeItem.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionData_StreamData_HandshakeItem proto.InternalMessageInfo

func (m *ConnectionData_StreamData_HandshakeItem) GetHtype() uint32 {
	if m != nil {
		return m.Htype
	}
	return 0
}

func (m *ConnectionData_StreamData_HandshakeItem) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

type ConnectionData_ExtensionItem struct {
	Etype                uint32   `protobuf:"varint,1,opt,name=etype,proto3" json:"etype,omitempty"`
	Len                  uint32   `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionData_ExtensionItem) Reset()         { *m = ConnectionData_ExtensionItem{} }
func (m *ConnectionData_ExtensionItem) String() string { return proto.CompactTextString(m) }
func (*ConnectionData_ExtensionItem) ProtoMessage()    {}
func (*ConnectionData_ExtensionItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 2}
}

func (m *ConnectionData_ExtensionItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionData_ExtensionItem.Unmarshal(m, b)
}
func (m *ConnectionData_ExtensionItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionData_ExtensionItem.Marshal(b, m, deterministic)
}
func (m *ConnectionData_ExtensionItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionData_ExtensionItem.Merge(m, src)
}
func (m *ConnectionData_ExtensionItem) XXX_Size() int {
	return xxx_messageInfo_ConnectionData_ExtensionItem.Size(m)
}
func (m *ConnectionData_ExtensionItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionData_ExtensionItem.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionData_ExtensionItem proto.InternalMessageInfo

func (m *ConnectionData_ExtensionItem) GetEtype() uint32 {
	if m != nil {
		return m.Etype
	}
	return 0
}

func (m *ConnectionData_ExtensionItem) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

type ConnectionData_DecodedInfo struct {
	Sni                  string   `protobuf:"bytes,1,opt,name=sni,proto3" json:"sni,omitempty"`
	SignatureSchemes     []uint32 `protobuf:"varint,2,rep,packed,name=signature_schemes,json=signatureSchemes,proto3" json:"signature_schemes,omitempty"`
	SupportedVersions    []uint32 `protobuf:"varint,3,rep,packed,name=supported_versions,json=supportedVersions,proto3" json:"supported_versions,omitempty"`
	SupportedGroups      []uint32 `protobuf:"varint,4,rep,packed,name=supported_groups,json=supportedGroups,proto3" json:"supported_groups,omitempty"`
	EcPointFormats       []uint32 `protobuf:"varint,5,rep,packed,name=ec_point_formats,json=ecPointFormats,proto3" json:"ec_point_formats,omitempty"`
	Oscp                 bool     `protobuf:"varint,6,opt,name=oscp,proto3" json:"oscp,omitempty"`
	Alpns                []string `protobuf:"bytes,7,rep,name=alpns,proto3" json:"alpns,omitempty"`
	KeyShareEntries      []uint32 `protobuf:"varint,8,rep,packed,name=key_share_entries,json=keyShareEntries,proto3" json:"key_share_entries,omitempty"`
	PskKeyExchangeModes  []uint32 `protobuf:"varint,9,rep,packed,name=psk_key_exchange_modes,json=pskKeyExchangeModes,proto3" json:"psk_key_exchange_modes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionData_DecodedInfo) Reset()         { *m = ConnectionData_DecodedInfo{} }
func (m *ConnectionData_DecodedInfo) String() string { return proto.CompactTextString(m) }
func (*ConnectionData_DecodedInfo) ProtoMessage()    {}
func (*ConnectionData_DecodedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 3}
}

func (m *ConnectionData_DecodedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionData_DecodedInfo.Unmarshal(m, b)
}
func (m *ConnectionData_DecodedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionData_DecodedInfo.Marshal(b, m, deterministic)
}
func (m *ConnectionData_DecodedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionData_DecodedInfo.Merge(m, src)
}
func (m *ConnectionData_DecodedInfo) XXX_Size() int {
	return xxx_messageInfo_ConnectionData_DecodedInfo.Size(m)
}
func (m *ConnectionData_DecodedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionData_DecodedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionData_DecodedInfo proto.InternalMessageInfo

func (m *ConnectionData_DecodedInfo) GetSni() string {
	if m != nil {
		return m.Sni
	}
	return ""
}

func (m *ConnectionData_DecodedInfo) GetSignatureSchemes() []uint32 {
	if m != nil {
		return m.SignatureSchemes
	}
	return nil
}

func (m *ConnectionData_DecodedInfo) GetSupportedVersions() []uint32 {
	if m != nil {
		return m.SupportedVersions
	}
	return nil
}

func (m *ConnectionData_DecodedInfo) GetSupportedGroups() []uint32 {
	if m != nil {
		return m.SupportedGroups
	}
	return nil
}

func (m *ConnectionData_DecodedInfo) GetEcPointFormats() []uint32 {
	if m != nil {
		return m.EcPointFormats
	}
	return nil
}

func (m *ConnectionData_DecodedInfo) GetOscp() bool {
	if m != nil {
		return m.Oscp
	}
	return false
}

func (m *ConnectionData_DecodedInfo) GetAlpns() []string {
	if m != nil {
		return m.Alpns
	}
	return nil
}

func (m *ConnectionData_DecodedInfo) GetKeyShareEntries() []uint32 {
	if m != nil {
		return m.KeyShareEntries
	}
	return nil
}

func (m *ConnectionData_DecodedInfo) GetPskKeyExchangeModes() []uint32 {
	if m != nil {
		return m.PskKeyExchangeModes
	}
	return nil
}

type ConnectionData_ClientHelloData struct {
	ClientVersion        uint32                          `protobuf:"varint,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	RandomLen            uint32                          `protobuf:"varint,2,opt,name=random_len,json=randomLen,proto3" json:"random_len,omitempty"`
	SessionIdLen         uint32                          `protobuf:"varint,3,opt,name=session_id_len,json=sessionIdLen,proto3" json:"session_id_len,omitempty"`
	SessionId            []byte                          `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CipherSuitesLen      uint32                          `protobuf:"varint,5,opt,name=cipher_suites_len,json=cipherSuitesLen,proto3" json:"cipher_suites_len,omitempty"`
	CipherSuites         []uint32                        `protobuf:"varint,6,rep,packed,name=cipher_suites,json=cipherSuites,proto3" json:"cipher_suites,omitempty"`
	CompressMethods      []uint32                        `protobuf:"varint,7,rep,packed,name=compress_methods,json=compressMethods,proto3" json:"compress_methods,omitempty"`
	ExtensionLen         int32                           `protobuf:"varint,8,opt,name=extension_len,json=extensionLen,proto3" json:"extension_len,omitempty"`
	Extensions           []*ConnectionData_ExtensionItem `protobuf:"bytes,9,rep,name=extensions,proto3" json:"extensions,omitempty"`
	ExtensionInfo        *ConnectionData_DecodedInfo     `protobuf:"bytes,10,opt,name=extension_info,json=extensionInfo,proto3" json:"extension_info,omitempty"`
	UseGrease            bool                            `protobuf:"varint,11,opt,name=use_grease,json=useGrease,proto3" json:"use_grease,omitempty"`
	Ja3                  string                          `protobuf:"bytes,12,opt,name=ja3,proto3" json:"ja3,omitempty"`
	Ja3Digest            string                          `protobuf:"bytes,13,opt,name=ja3_digest,json=ja3Digest,proto3" json:"ja3_digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ConnectionData_ClientHelloData) Reset()         { *m = ConnectionData_ClientHelloData{} }
func (m *ConnectionData_ClientHelloData) String() string { return proto.CompactTextString(m) }
func (*ConnectionData_ClientHelloData) ProtoMessage()    {}
func (*ConnectionData_ClientHelloData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 4}
}

func (m *ConnectionData_ClientHelloData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionData_ClientHelloData.Unmarshal(m, b)
}
func (m *ConnectionData_ClientHelloData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionData_ClientHelloData.Marshal(b, m, deterministic)
}
func (m *ConnectionData_ClientHelloData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionData_ClientHelloData.Merge(m, src)
}
func (m *ConnectionData_ClientHelloData) XXX_Size() int {
	return xxx_messageInfo_ConnectionData_ClientHelloData.Size(m)
}
func (m *ConnectionData_ClientHelloData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionData_ClientHelloData.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionData_ClientHelloData proto.InternalMessageInfo

func (m *ConnectionData_ClientHelloData) GetClientVersion() uint32 {
	if m != nil {
		return m.ClientVersion
	}
	return 0
}

func (m *ConnectionData_ClientHelloData) GetRandomLen() uint32 {
	if m != nil {
		return m.RandomLen
	}
	return 0
}

func (m *ConnectionData_ClientHelloData) GetSessionIdLen() uint32 {
	if m != nil {
		return m.SessionIdLen
	}
	return 0
}

func (m *ConnectionData_ClientHelloData) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *ConnectionData_ClientHelloData) GetCipherSuitesLen() uint32 {
	if m != nil {
		return m.CipherSuitesLen
	}
	return 0
}

func (m *ConnectionData_ClientHelloData) GetCipherSuites() []uint32 {
	if m != nil {
		return m.CipherSuites
	}
	return nil
}

func (m *ConnectionData_ClientHelloData) GetCompressMethods() []uint32 {
	if m != nil {
		return m.CompressMethods
	}
	return nil
}

func (m *ConnectionData_ClientHelloData) GetExtensionLen() int32 {
	if m != nil {
		return m.ExtensionLen
	}
	return 0
}

func (m *ConnectionData_ClientHelloData) GetExtensions() []*ConnectionData_ExtensionItem {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *ConnectionData_ClientHelloData) GetExtensionInfo() *ConnectionData_DecodedInfo {
	if m != nil {
		return m.ExtensionInfo
	}
	return nil
}

func (m *ConnectionData_ClientHelloData) GetUseGrease() bool {
	if m != nil {
		return m.UseGrease
	}
	return false
}

func (m *ConnectionData_ClientHelloData) GetJa3() string {
	if m != nil {
		return m.Ja3
	}
	return ""
}

func (m *ConnectionData_ClientHelloData) GetJa3Digest() string {
	if m != nil {
		return m.Ja3Digest
	}
	return ""
}

type ConnectionData_ServerHelloData struct {
	ServerVersion        uint32                          `protobuf:"varint,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	RandomLen            uint32                          `protobuf:"varint,2,opt,name=random_len,json=randomLen,proto3" json:"random_len,omitempty"`
	SessionIdLen         uint32                          `protobuf:"varint,3,opt,name=session_id_len,json=sessionIdLen,proto3" json:"session_id_len,omitempty"`
	SessionId            []byte                          `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CipherSuiteSel       uint32                          `protobuf:"varint,5,opt,name=cipher_suite_sel,json=cipherSuiteSel,proto3" json:"cipher_suite_sel,omitempty"`
	CompressMethodSel    uint32                          `protobuf:"varint,6,opt,name=compress_method_sel,json=compressMethodSel,proto3" json:"compress_method_sel,omitempty"`
	ExtensionLen         int32                           `protobuf:"varint,7,opt,name=extension_len,json=extensionLen,proto3" json:"extension_len,omitempty"`
	Extensions           []*ConnectionData_ExtensionItem `protobuf:"bytes,8,rep,name=extensions,proto3" json:"extensions,omitempty"`
	ExtensionInfo        *ConnectionData_DecodedInfo     `protobuf:"bytes,9,opt,name=extension_info,json=extensionInfo,proto3" json:"extension_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ConnectionData_ServerHelloData) Reset()         { *m = ConnectionData_ServerHelloData{} }
func (m *ConnectionData_ServerHelloData) String() string { return proto.CompactTextString(m) }
func (*ConnectionData_ServerHelloData) ProtoMessage()    {}
func (*ConnectionData_ServerHelloData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 5}
}

func (m *ConnectionData_ServerHelloData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionData_ServerHelloData.Unmarshal(m, b)
}
func (m *ConnectionData_ServerHelloData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionData_ServerHelloData.Marshal(b, m, deterministic)
}
func (m *ConnectionData_ServerHelloData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionData_ServerHelloData.Merge(m, src)
}
func (m *ConnectionData_ServerHelloData) XXX_Size() int {
	return xxx_messageInfo_ConnectionData_ServerHelloData.Size(m)
}
func (m *ConnectionData_ServerHelloData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionData_ServerHelloData.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionData_ServerHelloData proto.InternalMessageInfo

func (m *ConnectionData_ServerHelloData) GetServerVersion() uint32 {
	if m != nil {
		return m.ServerVersion
	}
	return 0
}

func (m *ConnectionData_ServerHelloData) GetRandomLen() uint32 {
	if m != nil {
		return m.RandomLen
	}
	return 0
}

func (m *ConnectionData_ServerHelloData) GetSessionIdLen() uint32 {
	if m != nil {
		return m.SessionIdLen
	}
	return 0
}

func (m *ConnectionData_ServerHelloData) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *ConnectionData_ServerHelloData) GetCipherSuiteSel() uint32 {
	if m != nil {
		return m.CipherSuiteSel
	}
	return 0
}

func (m *ConnectionData_ServerHelloData) GetCompressMethodSel() uint32 {
	if m != nil {
		return m.CompressMethodSel
	}
	return 0
}

func (m *ConnectionData_ServerHelloData) GetExtensionLen() int32 {
	if m != nil {
		return m.ExtensionLen
	}
	return 0
}

func (m *ConnectionData_ServerHelloData) GetExtensions() []*ConnectionData_ExtensionItem {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *ConnectionData_ServerHelloData) GetExtensionInfo() *ConnectionData_DecodedInfo {
	if m != nil {
		return m.ExtensionInfo
	}
	return nil
}

type ConnectionData_CertSummary struct {
	Digest               string   `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Issuer               string   `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject              string   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	IsCa                 bool     `protobuf:"varint,4,opt,name=is_ca,json=isCa,proto3" json:"is_ca,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionData_CertSummary) Reset()         { *m = ConnectionData_CertSummary{} }
func (m *ConnectionData_CertSummary) String() string { return proto.CompactTextString(m) }
func (*ConnectionData_CertSummary) ProtoMessage()    {}
func (*ConnectionData_CertSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 6}
}

func (m *ConnectionData_CertSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionData_CertSummary.Unmarshal(m, b)
}
func (m *ConnectionData_CertSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionData_CertSummary.Marshal(b, m, deterministic)
}
func (m *ConnectionData_CertSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionData_CertSummary.Merge(m, src)
}
func (m *ConnectionData_CertSummary) XXX_Size() int {
	return xxx_messageInfo_ConnectionData_CertSummary.Size(m)
}
func (m *ConnectionData_CertSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionData_CertSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionData_CertSummary proto.InternalMessageInfo

func (m *ConnectionData_CertSummary) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *ConnectionData_CertSummary) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *ConnectionData_CertSummary) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *ConnectionData_CertSummary) GetIsCa() bool {
	if m != nil {
		return m.IsCa
	}
	return false
}

func init() {
	proto.RegisterType((*CertificateData)(nil), "luids.tlsutil.v1.CertificateData")
	proto.RegisterType((*RecordData)(nil), "luids.tlsutil.v1.RecordData")
	proto.RegisterType((*ConnectionData)(nil), "luids.tlsutil.v1.ConnectionData")
	proto.RegisterType((*ConnectionData_ConnectionInfo)(nil), "luids.tlsutil.v1.ConnectionData.ConnectionInfo")
	proto.RegisterType((*ConnectionData_StreamData)(nil), "luids.tlsutil.v1.ConnectionData.StreamData")
	proto.RegisterType((*ConnectionData_StreamData_StreamInfo)(nil), "luids.tlsutil.v1.ConnectionData.StreamData.StreamInfo")
	proto.RegisterType((*ConnectionData_StreamData_PlaintextSummary)(nil), "luids.tlsutil.v1.ConnectionData.StreamData.PlaintextSummary")
	proto.RegisterType((*ConnectionData_StreamData_CiphertextSummary)(nil), "luids.tlsutil.v1.ConnectionData.StreamData.CiphertextSummary")
	proto.RegisterType((*ConnectionData_StreamData_HandshakeItem)(nil), "luids.tlsutil.v1.ConnectionData.StreamData.HandshakeItem")
	proto.RegisterType((*ConnectionData_ExtensionItem)(nil), "luids.tlsutil.v1.ConnectionData.ExtensionItem")
	proto.RegisterType((*ConnectionData_DecodedInfo)(nil), "luids.tlsutil.v1.ConnectionData.DecodedInfo")
	proto.RegisterType((*ConnectionData_ClientHelloData)(nil), "luids.tlsutil.v1.ConnectionData.ClientHelloData")
	proto.RegisterType((*ConnectionData_ServerHelloData)(nil), "luids.tlsutil.v1.ConnectionData.ServerHelloData")
	proto.RegisterType((*ConnectionData_CertSummary)(nil), "luids.tlsutil.v1.ConnectionData.CertSummary")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 1665 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xdd, 0x6e, 0x1c, 0x49,
	0x15, 0x96, 0x3d, 0xbf, 0x7d, 0xe6, 0xc7, 0xe3, 0x0e, 0x84, 0xde, 0x41, 0x61, 0x87, 0x04, 0xc4,
	0x40, 0x36, 0xe3, 0xc5, 0x96, 0x80, 0xd5, 0xc2, 0x05, 0xeb, 0x98, 0x5d, 0xc3, 0x66, 0x89, 0x7a,
	0x56, 0x48, 0x70, 0xd3, 0x2a, 0x57, 0x1f, 0xcf, 0x74, 0x66, 0xfa, 0x47, 0x55, 0xd5, 0x89, 0x7d,
	0xcb, 0x35, 0x3c, 0x05, 0x6f, 0xc0, 0x13, 0xf0, 0x1e, 0xdc, 0xf2, 0x08, 0xdc, 0x22, 0xa1, 0x73,
	0xaa, 0xba, 0xa7, 0xed, 0xec, 0xe2, 0x4d, 0x10, 0x88, 0x0b, 0xee, 0xaa, 0xbe, 0xfa, 0xce, 0x57,
	0xd5, 0x55, 0xe7, 0xab, 0x3a, 0x33, 0x30, 0x94, 0x79, 0x9a, 0xe6, 0xd9, 0xa2, 0x50, 0xb9, 0xc9,
	0xfd, 0xc9, 0xb6, 0x4c, 0x62, 0xbd, 0x30, 0x5b, 0x5d, 0x9a, 0x64, 0xbb, 0x78, 0xf9, 0xc3, 0xe9,
	0x87, 0xab, 0xc4, 0xac, 0xcb, 0x8b, 0x85, 0xcc, 0xd3, 0xa3, 0x55, 0xbe, 0x15, 0xd9, 0xea, 0x88,
	0xa9, 0x17, 0xe5, 0xe5, 0x51, 0x61, 0xae, 0x0b, 0xd4, 0x47, 0x26, 0x49, 0x51, 0x1b, 0x91, 0x16,
	0xbb, 0x96, 0x95, 0x7b, 0xf8, 0x21, 0x1c, 0x9c, 0xa2, 0x32, 0xc9, 0x65, 0x22, 0x85, 0xc1, 0xa7,
	0xc2, 0x08, 0xff, 0x3e, 0x74, 0xe3, 0x64, 0x85, 0xda, 0x04, 0x7b, 0xb3, 0xbd, 0xb9, 0x17, 0xba,
	0x9e, 0x3f, 0x81, 0x96, 0x12, 0xaf, 0x82, 0xfd, 0xd9, 0xde, 0x7c, 0x18, 0x52, 0xf3, 0xe1, 0xdf,
	0xf6, 0x00, 0x42, 0x94, 0xb9, 0x8a, 0x39, 0xf0, 0x9b, 0xe0, 0x69, 0xa3, 0x50, 0xa4, 0x51, 0x12,
	0xbb, 0xd8, 0xbe, 0x05, 0xce, 0x63, 0xff, 0x27, 0xe0, 0xd5, 0x73, 0xb3, 0xc6, 0xe0, 0x78, 0xba,
	0x58, 0xe5, 0xf9, 0x6a, 0x8b, 0x8b, 0x6a, 0xb9, 0x8b, 0xcf, 0x2b, 0x46, 0xb8, 0x23, 0xfb, 0x3e,
	0xb4, 0xe9, 0x2b, 0x82, 0xd6, 0x6c, 0x6f, 0xde, 0x09, 0xb9, 0x4d, 0x6b, 0xd9, 0x62, 0x16, 0xb4,
	0x19, 0xa2, 0xa6, 0x3f, 0x85, 0xbe, 0x4c, 0x8a, 0x35, 0x2a, 0x8c, 0x83, 0xce, 0x6c, 0x6f, 0xde,
	0x0f, 0xeb, 0xbe, 0xff, 0x2d, 0x80, 0x4b, 0x25, 0x56, 0x29, 0x66, 0x06, 0xe3, 0xa0, 0xcb, 0xa3,
	0x0d, 0xc4, 0x7f, 0x00, 0x90, 0xea, 0x95, 0x8e, 0x64, 0x5e, 0x66, 0x26, 0xe8, 0xb1, 0xa8, 0x47,
	0xc8, 0x29, 0x01, 0x0f, 0xff, 0x31, 0x83, 0xf1, 0x69, 0x9e, 0x65, 0x28, 0x4d, 0x92, 0x67, 0xfc,
	0xa9, 0x63, 0xd8, 0xaf, 0xbf, 0x71, 0x3f, 0x89, 0xfd, 0x53, 0x68, 0x27, 0xd9, 0x65, 0xee, 0x3e,
	0xec, 0x68, 0x71, 0xfb, 0x90, 0x16, 0x37, 0xe3, 0x1b, 0xdd, 0xf3, 0xec, 0x32, 0x0f, 0x39, 0xd8,
	0xff, 0x14, 0x06, 0x1a, 0xb3, 0x38, 0xb2, 0x7b, 0xc6, 0xdf, 0x3b, 0x38, 0x7e, 0x7c, 0xa7, 0xd6,
	0x92, 0xe9, 0xd4, 0x0c, 0x81, 0xe2, 0x6d, 0x9f, 0xd4, 0x94, 0x7c, 0x59, 0xab, 0xb5, 0xdf, 0x42,
	0x8d, 0xe2, 0x9d, 0xda, 0x12, 0x86, 0x72, 0x9b, 0x60, 0x66, 0xa2, 0x35, 0x6e, 0xb7, 0x39, 0x6f,
	0xf1, 0xe0, 0xf8, 0xfd, 0xbb, 0x3f, 0x94, 0x83, 0x3e, 0xa1, 0x18, 0xd6, 0x1c, 0xc8, 0x1d, 0x40,
	0xa2, 0x1a, 0xd5, 0x4b, 0x54, 0x4e, 0xb4, 0xfb, 0x15, 0x45, 0x97, 0x1c, 0xd4, 0x10, 0xd5, 0x3b,
	0xc0, 0xff, 0x75, 0xbd, 0x52, 0x89, 0xca, 0xe8, 0xa0, 0x37, 0x6b, 0xcd, 0x07, 0xc7, 0xef, 0xdd,
	0xbd, 0x52, 0x54, 0x66, 0x59, 0xa6, 0xa9, 0x50, 0xd7, 0xd5, 0x2a, 0x09, 0xd2, 0x24, 0xe8, 0x56,
	0x69, 0x05, 0xfb, 0x6f, 0x23, 0x68, 0x15, 0xac, 0x20, 0x25, 0xb4, 0x58, 0xe9, 0xc0, 0x9b, 0xb5,
	0xe6, 0x5e, 0xc8, 0xed, 0xe9, 0x1f, 0x5b, 0xcd, 0x1c, 0xa3, 0xa4, 0xf0, 0xdf, 0x87, 0x8e, 0x36,
	0x42, 0x59, 0x1b, 0xfe, 0x6b, 0xb7, 0x58, 0xa2, 0xff, 0x1e, 0xb4, 0x30, 0x8b, 0xbf, 0x82, 0xbb,
	0x88, 0xe6, 0x7f, 0x17, 0xc6, 0x71, 0xa9, 0x04, 0xcd, 0x17, 0x65, 0x1a, 0xa5, 0xe6, 0x8c, 0x6b,
	0x85, 0xa3, 0x0a, 0xfd, 0x8c, 0x40, 0x72, 0xb5, 0xdb, 0xcf, 0xa4, 0xe0, 0x2c, 0xf2, 0xc2, 0xbe,
	0x05, 0xce, 0x0b, 0xb6, 0xbc, 0xdd, 0x9b, 0xa4, 0xe0, 0x9c, 0x20, 0xcb, 0x33, 0x70, 0x5e, 0xf8,
	0xef, 0x82, 0xdb, 0xc7, 0xa8, 0xc8, 0x95, 0xe1, 0xd3, 0x1d, 0x85, 0x60, 0xa1, 0xe7, 0xb9, 0x32,
	0x44, 0x70, 0xd1, 0x4c, 0xe8, 0x59, 0x82, 0x85, 0x98, 0x30, 0x83, 0x41, 0x99, 0xc9, 0x3c, 0x2d,
	0xb6, 0x48, 0xce, 0xed, 0xb3, 0x73, 0x9b, 0x10, 0x7f, 0x04, 0x1a, 0x94, 0x06, 0xe3, 0x08, 0x95,
	0xca, 0x55, 0xe0, 0x31, 0x69, 0x54, 0xa1, 0x67, 0x04, 0xfa, 0x47, 0x70, 0xaf, 0x8e, 0x89, 0xd6,
	0x22, 0x8b, 0xf5, 0x5a, 0x6c, 0x30, 0x00, 0xe6, 0xfa, 0xf5, 0xd0, 0x27, 0xd5, 0xc8, 0xf4, 0x0f,
	0x23, 0x80, 0x9d, 0x15, 0x5e, 0xf3, 0xfb, 0x2f, 0x6f, 0xf8, 0xfd, 0x47, 0x6f, 0xe0, 0x2a, 0xd7,
	0x6c, 0xd8, 0x5e, 0xc0, 0xa8, 0xd8, 0x8a, 0x24, 0x33, 0x78, 0x65, 0x22, 0x21, 0xa5, 0x33, 0xfe,
	0x4f, 0xdf, 0x44, 0xf4, 0x79, 0x25, 0x50, 0x25, 0xdc, 0xb0, 0x96, 0xfc, 0xb9, 0x94, 0x7e, 0x0c,
	0x63, 0x7b, 0x19, 0xd6, 0x73, 0xd8, 0xeb, 0xe0, 0x67, 0x6f, 0x32, 0xc7, 0x69, 0xad, 0x50, 0x4d,
	0x32, 0xda, 0x89, 0xd2, 0x2c, 0xbf, 0x05, 0xa8, 0xb7, 0x56, 0x07, 0x1d, 0xb6, 0xc9, 0x07, 0x6f,
	0x32, 0x43, 0xbd, 0xfd, 0xe7, 0x06, 0xd3, 0xb0, 0x21, 0xe6, 0x3f, 0x82, 0x51, 0xdd, 0x8b, 0x74,
	0x99, 0x72, 0x32, 0x75, 0xc2, 0x61, 0x0d, 0x2e, 0xcb, 0x74, 0xfa, 0xfb, 0x76, 0x75, 0x66, 0xff,
	0x63, 0xfe, 0xd1, 0xe2, 0x55, 0x64, 0x97, 0xd2, 0xb6, 0x2f, 0x93, 0x16, 0xaf, 0x96, 0x3c, 0xe3,
	0x37, 0xa0, 0x47, 0x83, 0x34, 0xab, 0x7d, 0xb4, 0xba, 0x5a, 0xbc, 0x3a, 0xcb, 0x62, 0xff, 0xeb,
	0xd0, 0xd5, 0x4a, 0x92, 0xab, 0xba, 0x9c, 0x74, 0x1d, 0xad, 0xe4, 0x79, 0x41, 0x70, 0xac, 0xd9,
	0x89, 0x3d, 0x0b, 0xc7, 0x9a, 0x6c, 0xf8, 0x0e, 0xf4, 0x89, 0xcd, 0x2e, 0xea, 0xb3, 0x8b, 0x7a,
	0x5a, 0x49, 0xb6, 0xd0, 0x3b, 0xd0, 0xa7, 0x08, 0x1e, 0xf2, 0xec, 0x50, 0xac, 0xad, 0xfd, 0xbe,
	0x06, 0x9d, 0x8b, 0x6b, 0x83, 0x9a, 0x6d, 0xd0, 0x0a, 0x6d, 0xc7, 0x0f, 0xa0, 0x57, 0x08, 0xb9,
	0x41, 0xa3, 0x83, 0x01, 0xe3, 0x55, 0x97, 0x1e, 0xdd, 0x8b, 0x42, 0x07, 0xc3, 0xd9, 0xde, 0x7c,
	0x3f, 0xa4, 0x26, 0x21, 0x45, 0xa1, 0x83, 0x91, 0x45, 0x8a, 0x42, 0x7f, 0x81, 0x1f, 0xc7, 0x5f,
	0xe4, 0xc7, 0x07, 0x00, 0x3c, 0x1a, 0xf1, 0xcb, 0x7e, 0xc0, 0xdf, 0xe2, 0x31, 0xf2, 0x39, 0x3d,
	0xef, 0x1f, 0xd4, 0xc3, 0x49, 0x8a, 0xc1, 0xe4, 0xee, 0x6a, 0xc1, 0x86, 0x26, 0x29, 0x4e, 0xff,
	0xbe, 0x0f, 0x93, 0xdb, 0x6e, 0xa0, 0x8b, 0x66, 0xad, 0x37, 0x91, 0xe2, 0x5a, 0x45, 0x73, 0x42,
	0xb4, 0x42, 0x58, 0xeb, 0x8d, 0xad, 0x5e, 0xf8, 0x90, 0x88, 0x60, 0xb7, 0x63, 0x9f, 0x87, 0xfb,
	0x6b, 0xbd, 0xf9, 0x88, 0x77, 0xe4, 0x11, 0x8c, 0xc4, 0x16, 0x95, 0xa9, 0xe3, 0xed, 0x39, 0x0f,
	0x19, 0xac, 0x14, 0xde, 0x85, 0x81, 0x25, 0x59, 0x8d, 0xb6, 0x9d, 0x82, 0x21, 0xab, 0x42, 0xb7,
	0xa1, 0xdc, 0x69, 0x74, 0x2c, 0x41, 0x4a, 0xd3, 0x58, 0x03, 0x11, 0x6c, 0x7c, 0xd7, 0xae, 0x41,
	0x4a, 0x17, 0xfd, 0x3d, 0x38, 0x10, 0x45, 0x11, 0x0b, 0x23, 0x6a, 0x85, 0x1e, 0x53, 0xc6, 0x0e,
	0xae, 0x54, 0x68, 0xb1, 0x8e, 0x68, 0x95, 0xfa, 0x6e, 0xb1, 0x16, 0xb4, 0x6a, 0x4f, 0xc0, 0xdf,
	0x95, 0x3f, 0xb5, 0xa0, 0xc7, 0x9e, 0x3a, 0xdc, 0x8d, 0x54, 0x9a, 0xdf, 0x86, 0x61, 0x2a, 0xae,
	0xa2, 0x14, 0xb5, 0x16, 0x2b, 0x97, 0x2f, 0x9d, 0x70, 0x90, 0x8a, 0xab, 0x67, 0x0e, 0x9a, 0xfe,
	0x69, 0x1f, 0x0e, 0x5f, 0xbb, 0x20, 0xfe, 0xbf, 0xef, 0x37, 0xf7, 0x7d, 0xfa, 0x63, 0x18, 0xdd,
	0xb8, 0xe3, 0xc8, 0x82, 0x6b, 0xb6, 0xc0, 0x1e, 0x5b, 0xd3, 0x76, 0xaa, 0xea, 0x76, 0x9f, 0x31,
	0x6a, 0x52, 0xe0, 0xd9, 0x95, 0xc1, 0x4c, 0x53, 0x71, 0xe0, 0x02, 0xb1, 0x19, 0x88, 0x5f, 0x12,
	0xf8, 0xd7, 0x7d, 0x18, 0x3c, 0x45, 0x99, 0xc7, 0x18, 0xf3, 0xa5, 0x38, 0x81, 0x96, 0xce, 0x12,
	0xf7, 0x92, 0x51, 0xd3, 0x7f, 0x0c, 0x87, 0x3a, 0x59, 0x65, 0xc2, 0x94, 0x0a, 0x23, 0x2d, 0xd7,
	0x98, 0xf2, 0x51, 0xb4, 0xe6, 0xa3, 0x70, 0x52, 0x0f, 0x2c, 0x2d, 0x4e, 0x89, 0xa3, 0xcb, 0x82,
	0x2e, 0x13, 0x8c, 0xa3, 0x97, 0xa8, 0x68, 0x3d, 0x74, 0x2e, 0xc4, 0x3e, 0xac, 0x47, 0x7e, 0xe3,
	0x06, 0xfc, 0xef, 0xc3, 0x64, 0x47, 0x5f, 0xa9, 0xbc, 0x2c, 0xe8, 0x84, 0x88, 0x7c, 0x50, 0xe3,
	0x1f, 0x33, 0xec, 0xcf, 0x61, 0x82, 0x74, 0x83, 0x25, 0x99, 0x89, 0x2e, 0x73, 0x95, 0x0a, 0x63,
	0x9f, 0x90, 0x51, 0x38, 0x46, 0xf9, 0x9c, 0xe0, 0x5f, 0x58, 0x94, 0xca, 0xa7, 0x5c, 0xcb, 0xc2,
	0xd5, 0xf1, 0xdc, 0xa6, 0xed, 0x10, 0xdb, 0x22, 0xb3, 0xd5, 0x9e, 0x17, 0xda, 0x8e, 0xff, 0x03,
	0x38, 0xdc, 0xe0, 0x75, 0xa4, 0xd7, 0x42, 0x61, 0x84, 0x99, 0x51, 0x09, 0xda, 0xf2, 0x6d, 0x14,
	0x1e, 0x6c, 0xf0, 0x7a, 0x49, 0xf8, 0x99, 0x85, 0xfd, 0x13, 0xb8, 0x5f, 0xe8, 0x4d, 0x44, 0x7c,
	0xbc, 0x92, 0x6b, 0x91, 0xad, 0x30, 0x4a, 0xf3, 0x18, 0x6d, 0x99, 0x36, 0x0a, 0xef, 0x15, 0x7a,
	0xf3, 0x2b, 0xbc, 0x3e, 0x73, 0x63, 0xcf, 0x68, 0x68, 0xfa, 0xe7, 0x36, 0x1c, 0xdc, 0xaa, 0x70,
	0xe9, 0x06, 0x74, 0x55, 0x8f, 0xdb, 0x1f, 0x77, 0x44, 0x23, 0x8b, 0xba, 0xbd, 0xa1, 0x1b, 0x50,
	0x89, 0x2c, 0xce, 0xd3, 0x68, 0x77, 0x62, 0x9e, 0x45, 0x3e, 0xc5, 0xcc, 0xff, 0x0e, 0x8c, 0x35,
	0x6a, 0x62, 0x46, 0x49, 0xcc, 0x94, 0x16, 0x53, 0x86, 0x0e, 0x3d, 0x8f, 0x89, 0xf5, 0x00, 0x60,
	0xc7, 0xe2, 0xdc, 0x1f, 0x86, 0x5e, 0xcd, 0xa0, 0xef, 0xb7, 0x2f, 0x74, 0xa4, 0xcb, 0xc4, 0xa0,
	0x66, 0x9d, 0x0e, 0xeb, 0x1c, 0xd8, 0x81, 0x25, 0xe3, 0x24, 0xf5, 0x08, 0x46, 0x37, 0xb8, 0x41,
	0x97, 0x3f, 0x7b, 0xd8, 0xe4, 0xd1, 0x79, 0x52, 0xad, 0xa4, 0x50, 0xeb, 0x28, 0x45, 0xb3, 0xce,
	0x63, 0xbb, 0xe3, 0xa4, 0xe7, 0xf0, 0x67, 0x16, 0x26, 0x3d, 0xac, 0x32, 0x96, 0xe7, 0xed, 0xdb,
	0x17, 0xbb, 0x06, 0x69, 0xd2, 0xcf, 0x00, 0xea, 0xbe, 0xdd, 0xe8, 0xc1, 0xf1, 0xe2, 0xce, 0x8a,
	0xe1, 0x86, 0x13, 0xc2, 0x86, 0x82, 0xbf, 0x84, 0xf1, 0x6e, 0x52, 0x2e, 0xd0, 0x80, 0xdf, 0x8e,
	0xbb, 0x8b, 0xf5, 0x86, 0x47, 0xc2, 0xdd, 0xc2, 0xd9, 0x32, 0x0f, 0x00, 0x4a, 0x8d, 0xd1, 0x4a,
	0xa1, 0xd0, 0xc8, 0x6f, 0x62, 0x3f, 0xf4, 0x4a, 0x8d, 0x1f, 0x33, 0x40, 0x8e, 0x7a, 0x21, 0x4e,
	0xf8, 0x55, 0xf4, 0x42, 0x6a, 0x52, 0xc0, 0x0b, 0x71, 0x12, 0xb9, 0x1f, 0xd1, 0x23, 0xfb, 0xb8,
	0xbd, 0x10, 0x27, 0x4f, 0x19, 0x98, 0xfe, 0xa5, 0x05, 0x07, 0xb7, 0x7e, 0xc1, 0x50, 0xd2, 0xb8,
	0x4a, 0xf8, 0x56, 0xd2, 0x58, 0xf4, 0xbf, 0x99, 0x34, 0x73, 0x98, 0x34, 0x13, 0x21, 0xd2, 0xb8,
	0x75, 0x39, 0x33, 0x6e, 0xe4, 0xc2, 0x12, 0xb7, 0xfe, 0xc2, 0x16, 0xd5, 0x8d, 0x6c, 0x60, 0xb2,
	0xad, 0xf3, 0x0f, 0x6f, 0x26, 0x04, 0xf1, 0x5f, 0x4b, 0x89, 0xde, 0x9d, 0x29, 0xd1, 0xff, 0x0f,
	0xa4, 0x84, 0xf7, 0x6f, 0xa7, 0xc4, 0x74, 0x0b, 0x83, 0xc6, 0xaf, 0xbb, 0x2f, 0xfd, 0xc7, 0xe4,
	0x3e, 0x74, 0x13, 0xad, 0x4b, 0x54, 0x7c, 0x54, 0x5e, 0xe8, 0x7a, 0x54, 0x62, 0xe9, 0xf2, 0xe2,
	0x05, 0x4a, 0xc3, 0x07, 0xe4, 0x85, 0x55, 0xd7, 0xbf, 0x07, 0x9d, 0x44, 0x47, 0x52, 0xb8, 0x42,
	0xb1, 0x9d, 0xe8, 0x53, 0xf1, 0xd1, 0x93, 0xdf, 0x3d, 0x6e, 0xfc, 0xc5, 0xc3, 0xcb, 0x7e, 0x92,
	0xe4, 0x47, 0x32, 0x57, 0x68, 0xff, 0xe9, 0x59, 0x61, 0x76, 0xe4, 0xbe, 0xa3, 0xb8, 0xb8, 0xe8,
	0x32, 0x76, 0xf2, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xee, 0x19, 0xad, 0x38, 0x12, 0x00,
	0x00,
}
