// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resolv.proto

package dnsutilpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResolvCollectRequest struct {
	ClientIp             string   `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ResolvedIps          []string `protobuf:"bytes,3,rep,name=resolved_ips,json=resolvedIps,proto3" json:"resolved_ips,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvCollectRequest) Reset()         { *m = ResolvCollectRequest{} }
func (m *ResolvCollectRequest) String() string { return proto.CompactTextString(m) }
func (*ResolvCollectRequest) ProtoMessage()    {}
func (*ResolvCollectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993e7e3c415ddf0b, []int{0}
}

func (m *ResolvCollectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvCollectRequest.Unmarshal(m, b)
}
func (m *ResolvCollectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvCollectRequest.Marshal(b, m, deterministic)
}
func (m *ResolvCollectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvCollectRequest.Merge(m, src)
}
func (m *ResolvCollectRequest) XXX_Size() int {
	return xxx_messageInfo_ResolvCollectRequest.Size(m)
}
func (m *ResolvCollectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvCollectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvCollectRequest proto.InternalMessageInfo

func (m *ResolvCollectRequest) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *ResolvCollectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResolvCollectRequest) GetResolvedIps() []string {
	if m != nil {
		return m.ResolvedIps
	}
	return nil
}

type ResolvCheckRequest struct {
	ClientIp             string   `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ResolvedIp           string   `protobuf:"bytes,2,opt,name=resolved_ip,json=resolvedIp,proto3" json:"resolved_ip,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvCheckRequest) Reset()         { *m = ResolvCheckRequest{} }
func (m *ResolvCheckRequest) String() string { return proto.CompactTextString(m) }
func (*ResolvCheckRequest) ProtoMessage()    {}
func (*ResolvCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993e7e3c415ddf0b, []int{1}
}

func (m *ResolvCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvCheckRequest.Unmarshal(m, b)
}
func (m *ResolvCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvCheckRequest.Marshal(b, m, deterministic)
}
func (m *ResolvCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvCheckRequest.Merge(m, src)
}
func (m *ResolvCheckRequest) XXX_Size() int {
	return xxx_messageInfo_ResolvCheckRequest.Size(m)
}
func (m *ResolvCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvCheckRequest proto.InternalMessageInfo

func (m *ResolvCheckRequest) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *ResolvCheckRequest) GetResolvedIp() string {
	if m != nil {
		return m.ResolvedIp
	}
	return ""
}

func (m *ResolvCheckRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ResolvCheckResponse struct {
	Result               bool                 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	LastTs               *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_ts,json=lastTs,proto3" json:"last_ts,omitempty"`
	StoreTs              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=store_ts,json=storeTs,proto3" json:"store_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResolvCheckResponse) Reset()         { *m = ResolvCheckResponse{} }
func (m *ResolvCheckResponse) String() string { return proto.CompactTextString(m) }
func (*ResolvCheckResponse) ProtoMessage()    {}
func (*ResolvCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_993e7e3c415ddf0b, []int{2}
}

func (m *ResolvCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvCheckResponse.Unmarshal(m, b)
}
func (m *ResolvCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvCheckResponse.Marshal(b, m, deterministic)
}
func (m *ResolvCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvCheckResponse.Merge(m, src)
}
func (m *ResolvCheckResponse) XXX_Size() int {
	return xxx_messageInfo_ResolvCheckResponse.Size(m)
}
func (m *ResolvCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvCheckResponse proto.InternalMessageInfo

func (m *ResolvCheckResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *ResolvCheckResponse) GetLastTs() *timestamp.Timestamp {
	if m != nil {
		return m.LastTs
	}
	return nil
}

func (m *ResolvCheckResponse) GetStoreTs() *timestamp.Timestamp {
	if m != nil {
		return m.StoreTs
	}
	return nil
}

type SaveResolvRequest struct {
	ServerIp             string               `protobuf:"bytes,1,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	ClientIp             string               `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ResolvedIps          []string             `protobuf:"bytes,4,rep,name=resolved_ips,json=resolvedIps,proto3" json:"resolved_ips,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,5,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SaveResolvRequest) Reset()         { *m = SaveResolvRequest{} }
func (m *SaveResolvRequest) String() string { return proto.CompactTextString(m) }
func (*SaveResolvRequest) ProtoMessage()    {}
func (*SaveResolvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993e7e3c415ddf0b, []int{3}
}

func (m *SaveResolvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResolvRequest.Unmarshal(m, b)
}
func (m *SaveResolvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResolvRequest.Marshal(b, m, deterministic)
}
func (m *SaveResolvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResolvRequest.Merge(m, src)
}
func (m *SaveResolvRequest) XXX_Size() int {
	return xxx_messageInfo_SaveResolvRequest.Size(m)
}
func (m *SaveResolvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResolvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResolvRequest proto.InternalMessageInfo

func (m *SaveResolvRequest) GetServerIp() string {
	if m != nil {
		return m.ServerIp
	}
	return ""
}

func (m *SaveResolvRequest) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *SaveResolvRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SaveResolvRequest) GetResolvedIps() []string {
	if m != nil {
		return m.ResolvedIps
	}
	return nil
}

func (m *SaveResolvRequest) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type SaveResolvResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResolvResponse) Reset()         { *m = SaveResolvResponse{} }
func (m *SaveResolvResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResolvResponse) ProtoMessage()    {}
func (*SaveResolvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_993e7e3c415ddf0b, []int{4}
}

func (m *SaveResolvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResolvResponse.Unmarshal(m, b)
}
func (m *SaveResolvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResolvResponse.Marshal(b, m, deterministic)
}
func (m *SaveResolvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResolvResponse.Merge(m, src)
}
func (m *SaveResolvResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResolvResponse.Size(m)
}
func (m *SaveResolvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResolvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResolvResponse proto.InternalMessageInfo

func (m *SaveResolvResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ResolvCollectRequest)(nil), "luids.dnsutil.v1.ResolvCollectRequest")
	proto.RegisterType((*ResolvCheckRequest)(nil), "luids.dnsutil.v1.ResolvCheckRequest")
	proto.RegisterType((*ResolvCheckResponse)(nil), "luids.dnsutil.v1.ResolvCheckResponse")
	proto.RegisterType((*SaveResolvRequest)(nil), "luids.dnsutil.v1.SaveResolvRequest")
	proto.RegisterType((*SaveResolvResponse)(nil), "luids.dnsutil.v1.SaveResolvResponse")
}

func init() { proto.RegisterFile("resolv.proto", fileDescriptor_993e7e3c415ddf0b) }

var fileDescriptor_993e7e3c415ddf0b = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x6d, 0xec, 0x36, 0x1f, 0x13, 0x40, 0xb0, 0xa0, 0x2a, 0x32, 0x07, 0x8a, 0x09, 0xa8, 0x02,
	0xd5, 0x16, 0x89, 0x38, 0x71, 0x02, 0xc4, 0x21, 0xe2, 0x66, 0x22, 0x24, 0x10, 0x52, 0xe4, 0xd8,
	0x53, 0x67, 0xcb, 0xda, 0xbb, 0x78, 0xd6, 0x96, 0xfa, 0x53, 0xf8, 0x17, 0xfc, 0x44, 0x14, 0xaf,
	0x4d, 0x1c, 0x42, 0x93, 0x5e, 0xac, 0xf1, 0x68, 0xe6, 0xbd, 0x37, 0x6f, 0x66, 0xe1, 0x4e, 0x8e,
	0x24, 0x45, 0xe9, 0xa9, 0x5c, 0x6a, 0xc9, 0xee, 0x8b, 0x82, 0xc7, 0xe4, 0xc5, 0x19, 0x15, 0x9a,
	0x0b, 0xaf, 0x7c, 0xed, 0x4c, 0x13, 0xae, 0x57, 0xc5, 0xd2, 0x8b, 0x64, 0xea, 0x27, 0x52, 0x84,
	0x59, 0xe2, 0x57, 0xa5, 0xcb, 0xe2, 0xd2, 0x57, 0xfa, 0x5a, 0x21, 0xf9, 0x98, 0x2a, 0x7d, 0x6d,
	0xbe, 0x06, 0xc6, 0x79, 0x7b, 0xb8, 0x49, 0xf3, 0x14, 0x49, 0x87, 0xa9, 0xda, 0x44, 0xa6, 0xd9,
	0xbd, 0x82, 0x47, 0x41, 0xa5, 0xe9, 0x83, 0x14, 0x02, 0x23, 0x1d, 0xe0, 0xcf, 0x02, 0x49, 0xb3,
	0xc7, 0x30, 0x88, 0x04, 0xc7, 0x4c, 0x2f, 0xb8, 0x1a, 0x75, 0xce, 0x3a, 0xe7, 0x83, 0xa0, 0x6f,
	0x12, 0x33, 0xc5, 0x18, 0x1c, 0x67, 0x61, 0x8a, 0x23, 0xab, 0xca, 0x57, 0x31, 0x7b, 0xda, 0x0c,
	0x87, 0xf1, 0x82, 0x2b, 0x1a, 0xd9, 0x67, 0xf6, 0xf9, 0x20, 0x18, 0x36, 0xb9, 0x99, 0x22, 0xf7,
	0x12, 0x58, 0xcd, 0xb5, 0xc2, 0xe8, 0xc7, 0xad, 0x98, 0x9e, 0xc0, 0xb0, 0x85, 0x5a, 0x13, 0xc2,
	0x06, 0xf4, 0xaf, 0x14, 0x7b, 0x23, 0xc5, 0xfd, 0xd5, 0x81, 0x87, 0x5b, 0x44, 0xa4, 0x64, 0x46,
	0xc8, 0x4e, 0xa1, 0x9b, 0x23, 0x15, 0x42, 0x57, 0x34, 0xfd, 0xa0, 0xfe, 0x63, 0x53, 0xe8, 0x89,
	0x90, 0xf4, 0x42, 0x53, 0x45, 0x30, 0x9c, 0x38, 0x5e, 0x22, 0x65, 0x22, 0xd0, 0x6b, 0x7c, 0xf4,
	0xe6, 0x8d, 0x6d, 0x41, 0x77, 0x5d, 0x3a, 0x27, 0xf6, 0x06, 0xfa, 0xa4, 0x65, 0x8e, 0xeb, 0x2e,
	0xfb, 0x60, 0x57, 0xaf, 0xaa, 0x9d, 0x93, 0xfb, 0xbb, 0x03, 0x0f, 0x3e, 0x87, 0x25, 0x1a, 0x7d,
	0x2d, 0x0f, 0x08, 0xf3, 0x12, 0xf3, 0x96, 0x07, 0x26, 0x31, 0x53, 0xdb, 0x06, 0x59, 0x37, 0xac,
	0xc2, 0xde, 0xb3, 0x8a, 0xe3, 0x9d, 0x55, 0xb0, 0x97, 0x60, 0x69, 0x1a, 0x9d, 0x1c, 0xd4, 0x6d,
	0x69, 0x72, 0xc7, 0xc0, 0xda, 0x8a, 0x6b, 0x33, 0xef, 0x81, 0xc5, 0xe3, 0x5a, 0xab, 0xc5, 0xe3,
	0xc9, 0x77, 0xb8, 0xbb, 0x75, 0x48, 0xec, 0x13, 0xf4, 0x9a, 0xf0, 0x85, 0xf7, 0xef, 0xa5, 0x7b,
	0xff, 0x3b, 0x3a, 0xe7, 0x74, 0x47, 0xc9, 0xc7, 0xf5, 0x9d, 0xbb, 0x47, 0x13, 0x84, 0x61, 0x6b,
	0xa3, 0xec, 0x0b, 0x9c, 0x98, 0x60, 0x7c, 0x23, 0x72, 0xeb, 0xc4, 0x9c, 0xe7, 0x07, 0xaa, 0xcc,
	0x48, 0xee, 0xd1, 0xe4, 0xaa, 0x19, 0xe2, 0x5d, 0x1e, 0xad, 0x78, 0x89, 0xec, 0x2b, 0xc0, 0x66,
	0x76, 0xf6, 0x6c, 0x17, 0x67, 0x67, 0x97, 0xce, 0x78, 0x7f, 0x51, 0xc3, 0xf5, 0xfe, 0xe2, 0xdb,
	0xab, 0xd6, 0xc3, 0xad, 0x7a, 0x2e, 0xb8, 0xf4, 0x23, 0x99, 0xa3, 0x79, 0xbf, 0x09, 0x66, 0x7e,
	0x0d, 0xa2, 0x96, 0xcb, 0x6e, 0x95, 0x9b, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x73, 0x24, 0x86,
	0x80, 0x43, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResolvCollectClient is the client API for ResolvCollect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResolvCollectClient interface {
	Collect(ctx context.Context, in *ResolvCollectRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type resolvCollectClient struct {
	cc *grpc.ClientConn
}

func NewResolvCollectClient(cc *grpc.ClientConn) ResolvCollectClient {
	return &resolvCollectClient{cc}
}

func (c *resolvCollectClient) Collect(ctx context.Context, in *ResolvCollectRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/luids.dnsutil.v1.ResolvCollect/Collect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResolvCollectServer is the server API for ResolvCollect service.
type ResolvCollectServer interface {
	Collect(context.Context, *ResolvCollectRequest) (*empty.Empty, error)
}

// UnimplementedResolvCollectServer can be embedded to have forward compatible implementations.
type UnimplementedResolvCollectServer struct {
}

func (*UnimplementedResolvCollectServer) Collect(ctx context.Context, req *ResolvCollectRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Collect not implemented")
}

func RegisterResolvCollectServer(s *grpc.Server, srv ResolvCollectServer) {
	s.RegisterService(&_ResolvCollect_serviceDesc, srv)
}

func _ResolvCollect_Collect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvCollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolvCollectServer).Collect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luids.dnsutil.v1.ResolvCollect/Collect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolvCollectServer).Collect(ctx, req.(*ResolvCollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResolvCollect_serviceDesc = grpc.ServiceDesc{
	ServiceName: "luids.dnsutil.v1.ResolvCollect",
	HandlerType: (*ResolvCollectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Collect",
			Handler:    _ResolvCollect_Collect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resolv.proto",
}

// ResolvCheckClient is the client API for ResolvCheck service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResolvCheckClient interface {
	Check(ctx context.Context, in *ResolvCheckRequest, opts ...grpc.CallOption) (*ResolvCheckResponse, error)
}

type resolvCheckClient struct {
	cc *grpc.ClientConn
}

func NewResolvCheckClient(cc *grpc.ClientConn) ResolvCheckClient {
	return &resolvCheckClient{cc}
}

func (c *resolvCheckClient) Check(ctx context.Context, in *ResolvCheckRequest, opts ...grpc.CallOption) (*ResolvCheckResponse, error) {
	out := new(ResolvCheckResponse)
	err := c.cc.Invoke(ctx, "/luids.dnsutil.v1.ResolvCheck/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResolvCheckServer is the server API for ResolvCheck service.
type ResolvCheckServer interface {
	Check(context.Context, *ResolvCheckRequest) (*ResolvCheckResponse, error)
}

// UnimplementedResolvCheckServer can be embedded to have forward compatible implementations.
type UnimplementedResolvCheckServer struct {
}

func (*UnimplementedResolvCheckServer) Check(ctx context.Context, req *ResolvCheckRequest) (*ResolvCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}

func RegisterResolvCheckServer(s *grpc.Server, srv ResolvCheckServer) {
	s.RegisterService(&_ResolvCheck_serviceDesc, srv)
}

func _ResolvCheck_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolvCheckServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luids.dnsutil.v1.ResolvCheck/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolvCheckServer).Check(ctx, req.(*ResolvCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResolvCheck_serviceDesc = grpc.ServiceDesc{
	ServiceName: "luids.dnsutil.v1.ResolvCheck",
	HandlerType: (*ResolvCheckServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _ResolvCheck_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resolv.proto",
}

// ResolvArchiveClient is the client API for ResolvArchive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResolvArchiveClient interface {
	SaveResolv(ctx context.Context, in *SaveResolvRequest, opts ...grpc.CallOption) (*SaveResolvResponse, error)
}

type resolvArchiveClient struct {
	cc *grpc.ClientConn
}

func NewResolvArchiveClient(cc *grpc.ClientConn) ResolvArchiveClient {
	return &resolvArchiveClient{cc}
}

func (c *resolvArchiveClient) SaveResolv(ctx context.Context, in *SaveResolvRequest, opts ...grpc.CallOption) (*SaveResolvResponse, error) {
	out := new(SaveResolvResponse)
	err := c.cc.Invoke(ctx, "/luids.dnsutil.v1.ResolvArchive/SaveResolv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResolvArchiveServer is the server API for ResolvArchive service.
type ResolvArchiveServer interface {
	SaveResolv(context.Context, *SaveResolvRequest) (*SaveResolvResponse, error)
}

// UnimplementedResolvArchiveServer can be embedded to have forward compatible implementations.
type UnimplementedResolvArchiveServer struct {
}

func (*UnimplementedResolvArchiveServer) SaveResolv(ctx context.Context, req *SaveResolvRequest) (*SaveResolvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveResolv not implemented")
}

func RegisterResolvArchiveServer(s *grpc.Server, srv ResolvArchiveServer) {
	s.RegisterService(&_ResolvArchive_serviceDesc, srv)
}

func _ResolvArchive_SaveResolv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveResolvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolvArchiveServer).SaveResolv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luids.dnsutil.v1.ResolvArchive/SaveResolv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolvArchiveServer).SaveResolv(ctx, req.(*SaveResolvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResolvArchive_serviceDesc = grpc.ServiceDesc{
	ServiceName: "luids.dnsutil.v1.ResolvArchive",
	HandlerType: (*ResolvArchiveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveResolv",
			Handler:    _ResolvArchive_SaveResolv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resolv.proto",
}
